(ch-numpy-array)=
# 넘파이 어레이

넘파이<font size='2'>numpy</font>는 NUMerical PYthon의 줄임말이며,
파이썬 데이터 사이언스에서 가장 유용하게 활용되는 도구를 제공하는 라이브러리다.
넘파이가 제공하는 핵심 요소는 효율적으로 데이터를 저장하고 관리하는 1차원, 2차원, 3차원 등 다차원 어레이(배열)와
메모리 효율적이며 빠른 어레이 연산이다.

`numpy` 라이브러리는 관습적으로 별칭 `np`로 불러온다.

In [2]:
import numpy as np

## 다차원 어레이

넘파이 어레이는 리스트 자료형처럼 많은 데이터를 하나의 객체로 묶어 다루는 모음 자료형이며,
데이터 분석, 머신러닝, 딥러닝 등 다량의 데이터로 구성된 데이터셋을
처리할 때 일반적으로 활용된다.
아래 표에 리스트와 넘파이 어레이의 차이점을 정리하였다.

| 요소 | 리스트 | 넘파이 어레이 |
|------|--------|---------------|
| 데이터 저장 | 데이터 모음 | 데이터 모음 |
| 객체 속성 | 항목 저정 이외에 기타 속성 없음. | 값과 함께 데이터 저장 형식의 모양, 차원, 항목 자료형 등 객체의 메타 데이터를 속성으로 저장 |
| 메서드 | 기본 메서드 제공 | 데이터 과학에 유용한 많은 메서드 제공 |
| 자료형 제약 | 서로 다른 자료형 혼용 가능 | 모든 항목이 동일한 자료형으로 통일되어야 함 |
| 차원 | 차원 개념 없지만 중첩 리스트 지원 | 1차원, 2차원, 3차원, 4차원 등 다차원 구조 지원 |

여기서는 가장 많이 활용되는 1차원과 2차원 어레이의 사용법을 소개한다.

### 1차원 어레이

1차원 어레이는 중첩이 없는 리스트와 동일한 모양을 가지며, 리스트에 `np.array()` 함수를 적용하여 생성할 수 있다.
1차원 어레이는 **벡터**<font size='2'>vector</font>로도 불린다.

In [3]:
list_1D = [1, 17, -7.5, 3.14, 2.71828]
arr_1D = np.array(list_1D)

`arr_1D`는 `list_1D` 변수가 가리키는 리스트와 동일한 항목을 갖는 1차원 어레이를 가리킨다.

In [4]:
arr_1D

array([ 1.     , 17.     , -7.5    ,  3.14   ,  2.71828])

**항목 자료형**

리스트의 경우 임의의 자료형이 섞인 항목들을 가질 수 있지만
어레이는 항목들의 통일된 자료형을 요구한다.
따라서 위 출력 결과를 보면 `1`과 `17`이 각각 `1.`과 `17.` 변환되어 모든 항목이 부동소수점으로 구성되었다.
`1.`과 `17.`은 각각 `1.0`과 `17.0`을 가리킨다.
어레이 항목들의 통일된 자료형은 어레이 객체의 `dtype` 속성으로 확인된다.

In [5]:
arr_1D.dtype

dtype('float64')

**축**

1차원 어레이의 항목은 리스트처럼 왼쪽에서부터 오른쪽으로 하나의 방향으로만 이동하면서 확인할 수 있다.
이런 의미에서 1차원 어레이는 한 개의 **축**<font size='2'>axis</font>을 갖는다고 말한다.

**인덱스**

각 항목은 왼쪽에서부터 차례대로 0, 1, 2, ... 로 시작하는 **인덱스**를 갖는다.
예를 들어, `arr_1D`이 가리키는 1차원 어레이에 포함된 `-7.5`의 인덱스는 2다.

**차원**

어레이 자신의 차원은 `ndim` 속성에 할당되어 있다.

In [6]:
arr_1D.ndim

1

**모양**

어레이는 자신의 모양을 `shape` 속성에 튜플 자료형으로 저장한다.
1차원 어레이의 모양은 길이가 1인 튜플이며, 튜플의 유일한 항목은 1차원 어레이에 포함된 항목의 개수다.
`arr_1D`가 가리키는 1차원 어레이는 5개의 항목을 포함하기에 
모양은 `(5,)`이다.

In [7]:
arr_1D.shape

(5,)

:::{note} 쉼표의 중요성

길이가 1인 튜플은 `(5,)`처럼 반드시 쉼표가 포함되어 있음에 주의한다.
반면에 `(5)`는 그냥 정수 `5`와 동일하다. 즉, 튜플이 아닌 `int` 자료형이다.
:::

**어레이 객체 자료형**

넘파이 어레이 객체의 자료형은 항목 자료형, 차원, 모양과 상관없이 항상 `numpy.ndarray`다.
자료형은 `type()` 함수를 이용하여 확인한다.

In [8]:
type(arr_1D)

numpy.ndarray

### `np.arange()` 함수

`np.arange()` 함수는 `range()` 함수와 매우 유사한 기능을 갖지만, 리스트가 아닌 넘파이 어레이를 반환한다.
예를 들어, 아래 코드는 0부터 9 사이의 정수로 구성된 1차원 어레이를 생성한다.

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`range()` 함수와는 다르게 부동소수점을 스텝으로 사용할 수도 있으며,
그러면 부동소수점으로 구성된 1차원 어레이가 생성된다.
예를 들어, 아래 코드는 0부터 시작해서 스텝 0.1씩 증가시키면서 생성되는 값들로 구성된 1차원 어레이를 생성한다.
단, 오른쪽 끝값인 1 이전까지 스텝을 반복 적용한다.

In [10]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### 2차원 어레이

2차원 어레이의 모든 항목은 동일한 모양의 1차원 어레이어야 한다.
따라서 동일한 길이의 리스트를 항목으로 갖는 중첩 리스트를 2차원 어레이로 변환할 수 있다.
아래 코드는 길이가 4인 세 개의 리스트를 항목으로 갖는 중첩 리스트 `list_2D`를 2차원 어레이 `arr_2D`로 변환한다.

In [11]:
list_2D = [[1, 2, 3, 4],
           [5, 6, 7, 8],
           [9, 10, 11, 12]]
arr_2D = np.array(list_2D)

arr_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**축과 행렬**

2차원 어레이는 **행**<font size='2'>row</font>과 **열**<font size='2'>column</font>
두 개의 축을 가지며, 행은 0번 축, 열은 1번 축이라 부르기도 한다. 
행과 열을 갖는다는 의미에서 **행렬**<font size='2'>matrix</font>로 불린다.
예를 들어, `arr_2D`는 3개의 행과 4개의 열을 갖는 아래 모양의 행렬에 대응한다.

$$
\begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8\\
9 & 10 & 11 & 12
\end{bmatrix}
$$

**행과 열 인덱스**

인덱스는 축별로 지정된다.
위 2차원 어레이의 경우 3개의 행에 대해 맨 위 행부터 차례대로 0, 1, 2 행 인덱스가,
4개의 열에 대해 맨 왼쪽 열부터 차례대로 0, 1, 2, 3 열 인덱스가 지정된다.
2차원 어레이에 포함된 모든 항목의 위치는 행과 열 인덱스를 조합해서 지정된다.
예를 들어, 정수 7의 위치는 1번 행 인덱스와 2번 열 인덱스로 특정된다.

**차원**

차원은 축의 개수로 지정되며, 따라서 `arr_2D`는 행과 열 두 개의 축을 갖는 2차원 어레이다.

In [12]:
arr_2D.ndim

2

**모양**

2차원 어레이의 모양은 행과 열의 개수를 항목으로 갖는, 길이가 2인 튜플이다.
`arr_2D`는 3개의 행과 4개의 열을 갖기에 `(3, 4)` 모양의 어레이다.

In [13]:
arr_2D.shape

(3, 4)

**어레이 객체 자료형**

2차원 어레이의 자료형도 항목 자료형, 모양과 무관하게 `numpy.ndarray`다.

In [14]:
type(arr_2D)

numpy.ndarray

### 연습문제

(1) 1차원 어레이 생성 및 속성 확인

다음 조건을 만족하는 1차원 어레이를 생성하고, 해당 어레이의 항목 자료형(`dtype`), 차원(`ndim`), 모양(`shape`)을 출력하는 코드를 작성하라.

> 2.5부터 시작하여 0.5씩 증가하는 값으로 구성된 어레이 (단, 5.0 이전까지)

답:

In [7]:
import numpy as np

# 어레이 생성
arr_ex1 = np.arange(2.5, 5.0, 0.5)

# 속성 출력
print("어레이:", arr_ex1)
print("항목 자료형(dtype):", arr_ex1.dtype)
print("차원(ndim):", arr_ex1.ndim)
print("모양(shape):", arr_ex1.shape)

어레이: [2.5 3.  3.5 4.  4.5]
항목 자료형(dtype): float64
차원(ndim): 1
모양(shape): (5,)


(2) 2차원 어레이 생성 및 속성 확인

아래의 학생별 과목 점수 데이터를 2차원 어레이로 생성하고, 어레이의 모양(`shape`)과 차원(`ndim`)을 출력하는 코드를 작성하라.

- 학생 A: [85, 92, 78]
- 학생 B: [90, 88, 95]
- 학생 C: [76, 85, 80]
- 학생 D: [88, 90, 92]

답:

In [9]:
import numpy as np

# 중첩 리스트를 이용한 2차원 어레이 생성
scores = [[85, 92, 78],
          [90, 88, 95],
          [76, 85, 80],
          [88, 90, 92]]

arr_scores = np.array(scores)

# 속성 출력
print("어레이:\n", arr_scores)
print()
print("모양(shape):", arr_scores.shape)
print("차원(ndim):", arr_scores.ndim)

어레이:
 [[85 92 78]
 [90 88 95]
 [76 85 80]
 [88 90 92]]

모양(shape): (4, 3)
차원(ndim): 2


(3) 리스트와 어레이의 자료형 제약 비교

다음 리스트 `mixed_list`를 넘파이 어레이로 변환하는 코드를 작성하세요. 
변환된 어레이를 출력하고, 어레이의 항목 자료형(`dtype`)이 어떻게 결정되었는지 그 이유를 설명하라.

In [10]:
mixed_list = [10, 20, 3.14, 40]

답:

In [11]:
import numpy as np

mixed_list = [10, 20, 3.14, 40]
arr_mixed = np.array(mixed_list)

print("변환된 어레이:", arr_mixed)
print("항목 자료형(dtype):", arr_mixed.dtype)

변환된 어레이: [10.   20.    3.14 40.  ]
항목 자료형(dtype): float64


설명:

리스트는 서로 다른 자료형(정수와 부동소수점)을 함께 가질 수 있지만, 넘파이 어레이는 모든 항목이 동일한 자료형으로 통일되어야 한다.
`mixed_list`에는 부동소수점(`3.14`)이 포함되어 있으므로, 데이터의 손실을 막기 위해 정수 항목들(`10`, `20`, `40`)이 모두 부동소수점(`10.`, `20.`, `40.`)으로 자동 변환된다.
따라서 어레이의 `dtype`은 `float64`로 결정된다.

## 주요 항목 자료형

데이터 분석, 머신러닝, 딥러닝 등에서 사용되는 넘파이 어레이는
거의 대부분 부동소수점, 정수, 그리고 문자열로 구성된다.

### 부동소수점 자료형

부동소수점으로 구성된 `arr_1D`의 `dtype`은 부동소수점 자료형인 `float64`다.

In [23]:
print('arr_1D:', arr_1D)
print("arr_1D dtype:", arr_1D.dtype)

arr_1D: [ 1.      17.      -7.5      3.14     2.71828]
arr_1D dtype: float64


`float64`에서 64는 넘파이 어레이가 각각의 부동소수점을 저장하기 위해 64비트 크기의 메모리 공간을 할당한다는 의미다.
아래 코드는 `arr_1D`가 가리키는 어레이가 메모리상에서 총 40바이트를 사용함을 확인해준다.

In [24]:
print("항목 자료형:", arr_1D.dtype)
print("어레이 크기 (바이트):", arr_1D.nbytes)

항목 자료형: float64
어레이 크기 (바이트): 40


참고로 1바이트는 8비트에 해당한다.
`arr_1D`가 가리키는 어레이는 총 5개의 부동소수점이 포함되고 하나의 부동소수점이 8바이트 공간을 사용하기에,
총 `5 * 8 = 40` 바이트를 어레이가 차지한다.
어레이의 항목 하나가 차지하는 메모리 크기는 `itemsize` 속성에,
어레이에 포함된 항목의 개수는 `size` 속성에 저장되어 `nbytes`를 다음가 같이 계산할 수도 있다.

In [25]:
print("항목 크기 (바이트):", arr_1D.itemsize)
print("항목 수:", arr_1D.size)
print("전체 크기 (바이트):", arr_1D.itemsize * arr_1D.size)

항목 크기 (바이트): 8
항목 수: 5
전체 크기 (바이트): 40


머신러닝, 딥러닝에서 경우에 다루는 빅데이터는 항목의 개수가 수억개 이상인 경우도 있어서
그런 경우엔 메모리 사용량을 줄이기 위해 64비트 형식의 부동소수점 대신에 32비트, 16비트 형식을 사용하기도 한다.
아래 코드는 `arr_1D`를 생성할 때 `dtype`을 지정하는 방식으로 16비트 형식의 부동소수점을 사용하도록 강제한다.

In [26]:
arr_1D_16 = np.array(list_1D, dtype='float16')
arr_1D_16.dtype

dtype('float16')

기존에 생성된 어레이의 `dtype`을 `astype()` 메서드를 이용하여 변경할 수도 있다.
예를 들어, 아래 코드는 64비트가 아닌 8비트 형식의 부동소수점을 사용하도록 강제한다.

In [27]:
arr_1D_16 = arr_1D.astype('float16')

항목에 포함된 부동소수점이 2바이트만으로는 제대로 다뤄지지 않은 경우에는
소수점 이하 특정 자리에서 잘릴 수도 있다.
예를 들어, 5번째 항목이 `2.71828`에서 `2.719`로 소수점 이하 넷째 자리에서 반올림된 형식으로 지정된다.

In [28]:
arr_1D_16

array([ 1.   , 17.   , -7.5  ,  3.14 ,  2.719], dtype=float16)

항목 자료형인 `dtype`은 지정한대로 `float16`으로 확인된다.

In [29]:
arr_1D_16.dtype

dtype('float16')

각 항목이 차지하는 메모리 공간이 4분의 1로 줄었기에 어레이가 차지하는 메모리 공간 또한 4분의 1로 줄어든 10바이트다.

In [30]:
print("항목 크기 (바이트):", arr_1D_16.itemsize)
print("항목 수:", arr_1D_16.size)
print("전체 크기 (바이트):", arr_1D_16.itemsize * arr_1D_16.size)

항목 크기 (바이트): 2
항목 수: 5
전체 크기 (바이트): 10


### 정수 자료형

정수로 구성된 `arr_2D`의 `dtype`은 정수 자료형인 `int64`다.

In [31]:
arr_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
print('arr_2D dtype:', arr_2D.dtype)

arr_2D dtype: int64


`int64`에서 64는 넘파이 어레이가 각각의 정수를 64비트 크기의 공간을 기본 크기로 사용한다는 의미다.
아래 코드는 `arr_2D`가 가리키는 어레이가 메모리상에서 총 96바이트를 사용함을 확인해준다.

In [33]:
arr_2D = np.array(list_2D)

print("항목 자료형:", arr_2D.dtype)
print("어레이 크기 (바이트):", arr_2D.nbytes)

항목 자료형: int64
어레이 크기 (바이트): 96


`arr_2D`가 가리키는 어레이는 총 12개의 정수가 포함되고 하나의 정수가 8바이트 공간을 차지하게
총 `12 * 8 = 96` 바이트를 어레이가 차지한다.

In [34]:
arr_2D.itemsize * arr_2D.size

96

빅데이터를 다룰 때 메모리 사용량을 줄이기 위해 64비트 형식의 정수 대신 32비트, 16비트, 심지어 8비트 형식의 정수를 사용하기도 한다.
아래 코드는 64비트가 아닌 8비트 형식의 정수를 사용하도록 강제한다.

In [35]:
arr_2D_8 = np.array(list_2D, dtype='int8')

또는 기존에 생성된 어레이를 `astype()` 메서드를 이용하여 `dtype`을 변경할 수도 있다.

In [36]:
arr_2D_8 = arr_2D.astype('int8')

항목에 포함된 정수가 최대 12이기에 1바이트만 사용해도 필요한 정수를 다루는 데에 충분하다.
실제로 어레이를 확인해도 겉모습은 동일하다.

In [37]:
arr_2D_8

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int8)

다만, `dtype`이 달라졌을 뿐이다.

In [38]:
arr_2D_8.dtype

dtype('int8')

각 항목이 차지하는 메모리 공간이 8분의 1로 줄었기에 어레이가 차지하는 메모리 공간 또한 8분의 1로 줄어든 12바이트다.

In [39]:
print("항목 크기 (바이트):", arr_2D_8.itemsize)
print("항목 수:", arr_2D_8.size)
print("전체 크기 (바이트):", arr_2D_8.itemsize * arr_2D_8.size)

항목 크기 (바이트): 1
항목 수: 12
전체 크기 (바이트): 12


### 문자열 자료형

문자열은 기본적으로 유니코드로 처리되며, 크기는 최장 길이의 문자열 항목에 맞춰 결정된다.
예를 들어 아래 코드는 어레이에 포함된 가장 긴 문자열 `'python'` 의 길이가 6이기에
`<U6`가 자료형으로 지정됨을 보여준다.
즉, 어레이에 포함된 모든 문자열의 최대 길이가 6이라는 의미다.

In [40]:
arr_string = np.array(['python', 'data', 'numpy'])
arr_string.dtype

dtype('<U6')

:::{note} 유니코드

유니코드<font size='2'>Unicode</font>는 전 세계의 모든 문자를 하나의 표준 체계로 정의하고 각 문자에 고유한 번호(코드 포인트)를 부여하는 국제 문자 집합 표준이다. UTF-8, UTF-16 등의 다양한 인코딩 방식으로 컴퓨터에 저장된다.
:::

어레이를 생성할 때 `dtype='str'`을 지정하면 모든 항목을 문자열로 변환한다.
예를 들어, 아래 코드는 정수와 부동소수점으로 구성된 리스트의 항목을 모두 문자열로 변환하여
어레이를 생성한다.

In [41]:
numeric_1D_strings = np.array(list_1D, dtype='str')
numeric_1D_strings

array(['1', '17', '-7.5', '3.14', '2.71828'], dtype='<U7')

아래 어레이의 자료형은 `<U7`인데, 문자열 `'2.71828'` 길이가 7로 가장 크기 때문이다.

반면에 아래 코드는 `list_2D`에 포함된 모든 정수를 문자열로 변환하여 2차원 어레이를 생성하며,
`dtype`은 최대 2개의 기호를 사용하는 문자열로 구성되었기에 `'<U2'`로 지정된다.

In [42]:
numeric_2D_strings = np.array(list_2D, dtype='str')
numeric_2D_strings

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8'],
       ['9', '10', '11', '12']], dtype='<U2')

### 부울 자료형

참(`True`)과 거짓(`False`) 두 가지 값만 갖는 부울<font size='2'>boolean</font> 자료형으로 구성된 어레이의 `dtype`은 `bool`이다.
이처럼 항목 자료형이 `bool`인 어레이를 **부울 어레이**<font size='2'>Boolean array</font>라 부른다.
예를 들어, 아래 코드는 부울 값으로 구성된 리스트를 부울 어레이로 변환한다.

In [24]:
arr_bool = np.array([True, False, True, True])
arr_bool

array([ True, False,  True,  True])

부울 어레이의 항목 자료형은 `bool`로 확인된다.

In [25]:
arr_bool.dtype

dtype('bool')

부울 값은 내부적으로 1바이트(8비트)의 메모리 공간을 사용한다.
아래 코드는 4개의 부울 항목을 갖는 어레이가 총 4바이트를 차지함을 보여준다.

In [26]:
print("항목 크기 (바이트):", arr_bool.itemsize)
print("항목 수:", arr_bool.size)
print("전체 크기 (바이트):", arr_bool.nbytes)

항목 크기 (바이트): 1
항목 수: 4
전체 크기 (바이트): 4


기존의 숫자형 어레이를 `astype('bool')`을 이용하여 부울값으로만 구성된 어레이로 변환할 수도 있다.
이때 `0`과 `0.0`은 `False`로, 그 외의 모든 0이 아닌 숫자는 `True`로 변환된다.

In [27]:
arr_num = np.array([0, 1, -2.5, 0.0, 3])
arr_num_bool = arr_num.astype('bool')
arr_num_bool

array([False,  True,  True, False,  True])

### `object` 자료형

파이썬의 모든 자료형은 `object` 클래스를 상속한다.
즉, 임의의 값의 자료형은 항상 `object` 자료형이 된다.
따라서 넘파이 어레이를 정의할 때 `dtype=object`를 사용하면 
각 항목의 자료형을 그대로 보존하면서 어레이를 생성할 수 있다. 

In [ ]:
array_of_object = np.array([1, 'two', 3.0], dtype=object)
array_of_object

array([1, 'two', 3.0], dtype=object)

`object`를 항목 자료형으로 지정하면 여러 자료형을 그대로 유지하면서 하나의 어레이로 다룰 수 있다는 점에서 매우 유용하다.
하지만 `int64`, `float64`, `str` 등 특정 자료형으로 지정한 
경우에 비해 메모리 효율이 낮고 처리 속도가 느려진다는 점은 기억해 두어야 한다.

### 연습문제

(1) 어레이 자료형 변경 및 메모리 크기 비교

다음 1차원 정수 어레이 `arr_int`의 기본 항목 자료형(`dtype`)과 전체 메모리 크기(바이트)를 확인하라.
그 후, 이 어레이의 자료형을 16비트 정수형(`int16`)으로 변경한 새로운 어레이를 생성하고, 변경된 어레이의 전체 메모리 크기가 어떻게 달라졌는지 출력하라.

In [12]:
import numpy as np

arr_int = np.array([10, 20, 30, 40, 50])

답:

In [16]:
import numpy as np
arr_int = np.array([10, 20, 30, 40, 50])

print("기본 자료형:", arr_int.dtype)
print("기본 어레이 전체 크기(바이트):", arr_int.nbytes)

print("\n-- 자료형 변경 --\n")
print("int16으로 자료형 변경")
arr_int16 = arr_int.astype('int16')

print("변경된 자료형:", arr_int16.dtype)
print("변경된 어레이 전체 크기(바이트):", arr_int16.nbytes)

기본 자료형: int64
기본 어레이 전체 크기(바이트): 40

-- 자료형 변경 --

int16으로 자료형 변경
변경된 자료형: int16
변경된 어레이 전체 크기(바이트): 10


설명:

기본적으로 정수 어레이는 `int64`(항목당 8바이트)로 생성되므로 전체 크기는 40바이트다.
이를 `int16`(항목당 2바이트)으로 변경하면 전체 크기가 10바이트로 줄어들어 메모리 사용량을 크게 절약할 수 있다.

(2) 문자열 어레이의 자료형 이해

다음 리스트를 이용하여 넘파이 어레이를 생성하라.
생성된 어레이의 항목 자료형(`dtype`)을 확인하고, 해당 `dtype`이 의미하는 바를 설명하라.

In [17]:
words = ['apple', 'banana', 'strawberry', 'kiwi']

답:

In [18]:
import numpy as np

words = ['apple', 'banana', 'strawberry', 'kiwi']
arr_words = np.array(words)

print("어레이:", arr_words)
print("항목 자료형(dtype):", arr_words.dtype)

어레이: ['apple' 'banana' 'strawberry' 'kiwi']
항목 자료형(dtype): <U10


설명:

출력되는 `dtype`은 `<U10`이다.
이는 어레이 항목들이 유니코드 문자열로 처리되며,
포함된 문자열 중 가장 긴 단어인 `'strawberry'`의 길이(10글자)에 맞춰 최대 길이가 10인 문자열 자료형으로 자동 지정되었음을 의미한다.

(3) 부울 어레이 변환 및 메모리 크기 확인

다음 정수 어레이 `arr_scores`를 부울(`bool`) 자료형으로 변환한 새로운 어레이를 생성하라.
변환된 어레이를 출력하고, 변환 전과 후의 어레이 전체 메모리 크기(바이트)가 어떻게 달라졌는지 비교하여 설명하라.

In [28]:
import numpy as np
arr_scores = np.array([0, 85, 0, 92, -5])

답:

In [29]:
import numpy as np
arr_scores = np.array([0, 85, 0, 92, -5])

print("기본 어레이 전체 크기(바이트):", arr_scores.nbytes)

# bool 자료형으로 변환
arr_bool = arr_scores.astype('bool')

print("변환된 부울 어레이:", arr_bool)
print("변경된 어레이 전체 크기(바이트):", arr_bool.nbytes)

기본 어레이 전체 크기(바이트): 40
변환된 부울 어레이: [False  True False  True  True]
변경된 어레이 전체 크기(바이트): 5


설명:

정수 어레이를 부울(`bool`) 자료형으로 변환하면 `0`은 `False`로, `0`이 아닌 모든 숫자(`85`, `92`, `-5`)는 `True`로 변환된다. 
메모리 측면에서 기본 정수 어레이(`int64`)는 항목당 8바이트를 차지하여 총 40바이트(5개 항목)를 사용하지만,
부울 어레이는 항목당 1바이트만 차지하므로 전체 크기가 5바이트로 크게 줄어든다.

(4) `object` 자료형을 활용한 어레이 생성

정수, 부동소수점, 문자열이 섞여 있는 아래 리스트를 넘파이 어레이로 변환하려 한다.
각 항목의 원래 자료형을 그대로 유지하면서 어레이를 생성하는 코드를 작성하고, 생성된 어레이의 항목 자료형(`dtype`)을 확인하라.

In [19]:
mixed_data = [100, 3.14, 'Python']

답:

In [21]:
import numpy as np

mixed_data = [100, 3.14, 'Python']

print("원래 자료형을 유지하기 위해 dtype=object 지정")
arr_obj = np.array(mixed_data, dtype=object)

print("어레이:", arr_obj)
print("항목 자료형(dtype):", arr_obj.dtype)

print("\n각 항목의 실제 파이썬 자료형 확인")
for item in arr_obj:
    print(f"값: {item}, 자료형: {type(item)}")

원래 자료형을 유지하기 위해 dtype=object 지정
어레이: [100 3.14 'Python']
항목 자료형(dtype): object

각 항목의 실제 파이썬 자료형 확인
값: 100, 자료형: <class 'int'>
값: 3.14, 자료형: <class 'float'>
값: Python, 자료형: <class 'str'>


설명: 

일반적으로 서로 다른 자료형이 섞인 리스트를 어레이로 변환하면 문자열 등 하나의 자료형으로 강제 통일된다.
하지만 `dtype=object`를 지정하면 파이썬의 기본 객체 형태를 유지하므로, 정수(`int`), 부동소수점(`float`), 문자열(`str`) 고유의 자료형을 잃지 않고 하나의 어레이에 담을 수 있다.
단, 메모리 효율과 연산 속도는 일반적인 넘파이 어레이보다 떨어진다.

## 실전 예제: 붓꽃 데이터셋

붓꽃<font size='2'>Iris</font> 데이터셋은 1936년 통계학자 로날드 피셔<font size='2'>Ronald Fisher</font>에 의해 발표된 고전적인 데이터셋이다.
자동분류 문제를 연구하기 위해 수집되었으며, 세토사<font size='2'>Setosa</font>, 
버시컬러<font size='2'>Versicolor</font>, 
버지니카<font size='2'>Verginica</font> 등 
붓꽃의 세 가지 품종에 대해 꽃잎 길이와 너비, 꽃받침 길이와 너비 정보를 포함한 150개의 샘플로 구성되어 있다.

이 데이터셋은 데이터 분석과 기계학습 분야에서 가장 널리 사용되는 예제 데이터셋이다.

:::{note} 데이터 샘플 vs. 데이터셋

데이터 샘플<font size='2'>data</font>는 개별 정보 또는 값 자체를 의미하고, 
데이터셋<font size='2'>dataset</font>은 특정 목적을 위해 수집되고 구조화된 데이터 샘플의 모음을 의미한다.

| 구분 | 데이터 샘플 | 데이터셋 |
|------|--------|----------|
| 정의 | 개별 사실, 값, 관찰 결과 | 특정 목적으로 수집된 데이터의 집합 |
| 예시 | 175cm, 70kg (한 사람의 키, 체중) | 1,000명의 키, 몸무게, 나이 정보 |
| 구조 | 단일 값 | 표, 엑셀 파일 등 체계적으로 정리된 구조 |

### 데이터셋 저장소

데이터셋 저장소는 데이터 분석과 머신러닝 학습을 위해 수집하고 정리한 데이터셋들을 보관하는 공간이다.
본 강의노트는 실전에서 구한 데이터셋을 아래 저장소에서 다운로드하여 데이터 과학의 기초 개념을 소개하는
예제 위주로 구성된다.

In [4]:
data_url = 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

### CSV 파일

CSV 파일은 Comma-Separated Values의 약자로, 데이터를 쉼표로 구분하여 저장하는 단순한 텍스트 형식의 파일이며 확장자는 .csv이다. 각 행은 줄바꿈으로 구분되고, 행 안의 데이터는 쉼표로 나뉘어 엑셀과 같은 표 형태로 표현된다. 따라서 모든 행은 동일한 개수의 쉼표를 가지며, 행별 데이터 수가 일정하고, 
행별로 동일한 열에 위치한 값들은 동일한 특성을 공유한다.

CSV는 주로 간단한 표 데이터를 저장하고 공유하는 데 적합한 파일 형식이다. 구조가 단순하고 호환성이 뛰어나기 때문에 엑셀과 파이썬을 비롯한 다양한 편집기와 프로그래밍 언어에서 CSV 파일을 다루는 기능을 너비넓게 제공한다.

**`iris_dataset.csv` 파일**

`iris_dataset.csv` 파일에 붓꽃 데이터 150개가 아래 형식으로 저장되어 있다.
각 샘플은 꽃받침 길이와 너비, 꽃잎 길이와 너비 등 4개의 수치형 특성과 해당 샘플의 품종을 나타내는 문자열을 포함하고 있다.

:::{image} https://raw.githubusercontent.com/codingalzi/code-workout-datasci/master/images/iris_csv.png
:width: 80%
:align: center
:::

**헤더**

파일 첫행의 `sepal.length,sepal.width,petal.length,petal.width,variety`은 각각의 열에 포함된 데이터의 종류를
알려주는 **헤더**<font size='2'>header</font>다.
헤더는 열별 데이터셋을 대변하는 이름이며, 변수, 변인, 특성 등으로 불린다.
통계학 분야에서는 변수 또는 변인이, 데이터 분석과 머신러닝 분야에서는 특성이란 표현이 선호된다.

붓꽃 데이터셋에 포함된 5개 특성은 다음과 같다.

| 영어 특성명 | 한글 특성명 |
|------|------|
| sepal.length | 꽃받침 길이 |
| sepal.width | 꽃받침 너비 |
| petal.length | 꽃잎 길이 |
| petal.width | 꽃잎 너비 |
| variety | 품종 |

:::{image} https://raw.githubusercontent.com/codingalzi/code-workout-datasci/master/images/iris_petal-sepal.png
:width: 70%
:align: center
:::

### 1차원 어레이로 불러오기

`np.loadtxt()` 함수는 지정된 데이터 저장소나 폴더의 CSV 파일 등 텍스트 파일에 포함된 데이터를 불러와 넘파이 어레이 객체로 반환한다. 
이때 구분자(`delimiter`), 건너뛸 행(`skiprows`), 불러올 열(`usecols`), 항목 자료형(`dtype`) 등의 키워드 인자를
지정하여 원하는 데이터만 원하는 형식으로 선택적으로 불러올 수 있다.  

아래 코드에서는 `iris_dataset.csv` 파일을 읽어올 때 첫행인 헤더를 건너뛰고,
`usecols=0`키워드 인자를 지정하여 0번 열, 즉 꽃받침 길이 데이터가 포함된 열만 1차원 어레이로 가져온다.

In [45]:
iris_sepal_length = np.loadtxt(data_url+"iris.csv", delimiter=',', skiprows=1, dtype='float16', usecols=0)
iris_sepal_length

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9], dtype=float16)

반면에 아래 코드는 4번 열, 즉 꽃잎 너비 데이터를 담은 열만 1차원 어레이로 불러온다.

In [46]:
iris_variety = np.loadtxt(data_url+"iris.csv", delimiter=',', skiprows=1, dtype=str, usecols=4)
iris_variety

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

각 변수가 가리키는 값을 확인하면 `shape`이 `(150,)`, 즉 150개의 항목을 갖는 1차원 어레이라고 알려준다.
차원은 모양을 가리키는 튜플의 길이가 1인 것으로 확인된다.

In [47]:
iris_sepal_length.shape

(150,)

In [48]:
iris_variety.shape

(150,)

실제로 두 어레이의 `ndim` 속성을 확인하면 차원이 1로 확인된다.

In [49]:
iris_sepal_length.ndim

1

In [50]:
iris_variety.ndim

1

반면에 두 1차원 어레이의 항목 자료형은 서로 다르다.

In [51]:
iris_sepal_length.dtype

dtype('float16')

In [52]:
iris_variety.dtype

dtype('<U10')

### 2차원 어레이로 불러오기

**수치형 특성들만 2차원 어레이로 불러오기**

붓꽃 샘플별로 품종을 제외한 나머지 네 개의 특성으로 구성된 데이터만 불러오기 위해
`usecols=(0, 1, 2, 3)`을 지정한다.
즉, 0번 열부터 3번 열까지만 대상으로 `np.loadtxt()` 함수를 적용한다.
네 열에 포함된 데이터가 모두 부동소수점이기에 생성된 어레이의 항목 자료형은
`float64`로 자동 지정된다.

In [5]:
iris_features = np.loadtxt(data_url+"iris.csv", delimiter=',', skiprows=1, usecols=(0, 1, 2, 3))
iris_features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

아래 코드는 `iris_features`가 가리키는 어레이의 모양, 항목 자료형, 차원을 확인해준다.

In [10]:
print('모양:', iris_features.shape)
print('항목 자료형:', iris_features.dtype)
print('차원:', iris_features.ndim)

모양: (150, 4)
항목 자료형: float64
차원: 2


**품종 데이터까지 2차원 어레이로 불러오기**

품종 특성은 문자열로 구성되어 다른 열의 특성값들과 자료형이 다르다.
따라서 모든 데이터를 함께 넘파이 어레이로 불러오려면 `dtype='object'` 또는 `dtype='str'`로 지정해야 한다.
그러면 모든 값이 문자열로 변환되어 어레이에 포함된다.
모든 열(특성)을 2차원 어레이로 불러오려면 `usecols` 키워드 인자는 굳이 지정하지 않아도 된다.
물론 `usecols=(0, 1, 2, 3, 4)`로 모든 열을 지정해도 된다.

In [13]:
iris_full_object = np.loadtxt(data_url+"iris.csv", delimiter=',', skiprows=1, dtype=object)
iris_full_object

array([['5.1', '3.5', '1.4', '.2', 'Setosa'],
       ['4.9', '3', '1.4', '.2', 'Setosa'],
       ['4.7', '3.2', '1.3', '.2', 'Setosa'],
       ['4.6', '3.1', '1.5', '.2', 'Setosa'],
       ['5', '3.6', '1.4', '.2', 'Setosa'],
       ['5.4', '3.9', '1.7', '.4', 'Setosa'],
       ['4.6', '3.4', '1.4', '.3', 'Setosa'],
       ['5', '3.4', '1.5', '.2', 'Setosa'],
       ['4.4', '2.9', '1.4', '.2', 'Setosa'],
       ['4.9', '3.1', '1.5', '.1', 'Setosa'],
       ['5.4', '3.7', '1.5', '.2', 'Setosa'],
       ['4.8', '3.4', '1.6', '.2', 'Setosa'],
       ['4.8', '3', '1.4', '.1', 'Setosa'],
       ['4.3', '3', '1.1', '.1', 'Setosa'],
       ['5.8', '4', '1.2', '.2', 'Setosa'],
       ['5.7', '4.4', '1.5', '.4', 'Setosa'],
       ['5.4', '3.9', '1.3', '.4', 'Setosa'],
       ['5.1', '3.5', '1.4', '.3', 'Setosa'],
       ['5.7', '3.8', '1.7', '.3', 'Setosa'],
       ['5.1', '3.8', '1.5', '.3', 'Setosa'],
       ['5.4', '3.4', '1.7', '.2', 'Setosa'],
       ['5.1', '3.7', '1.5', '.4', 'Setosa'],


`np.loadtxt()` 함수의 `dtype=object` 키워드 인자를 지정해도 모든 열의 자료형이 문자열로 지정되는
`np.loadtxt()` 함수가 여러 자료형이 포함된 경우 문자열로 모든 값을 변환하여 불러오기 때문이다.
따라서 아래 코드에서처럼 차라리 `dtype='str` 지정하는 것이 자료형을 명확히 한다는 측면에서 보다 좋다.

In [14]:
iris_full_str = np.loadtxt(data_url+"iris.csv", delimiter=',', skiprows=1, dtype='str')
iris_full_str

array([['5.1', '3.5', '1.4', '.2', 'Setosa'],
       ['4.9', '3', '1.4', '.2', 'Setosa'],
       ['4.7', '3.2', '1.3', '.2', 'Setosa'],
       ['4.6', '3.1', '1.5', '.2', 'Setosa'],
       ['5', '3.6', '1.4', '.2', 'Setosa'],
       ['5.4', '3.9', '1.7', '.4', 'Setosa'],
       ['4.6', '3.4', '1.4', '.3', 'Setosa'],
       ['5', '3.4', '1.5', '.2', 'Setosa'],
       ['4.4', '2.9', '1.4', '.2', 'Setosa'],
       ['4.9', '3.1', '1.5', '.1', 'Setosa'],
       ['5.4', '3.7', '1.5', '.2', 'Setosa'],
       ['4.8', '3.4', '1.6', '.2', 'Setosa'],
       ['4.8', '3', '1.4', '.1', 'Setosa'],
       ['4.3', '3', '1.1', '.1', 'Setosa'],
       ['5.8', '4', '1.2', '.2', 'Setosa'],
       ['5.7', '4.4', '1.5', '.4', 'Setosa'],
       ['5.4', '3.9', '1.3', '.4', 'Setosa'],
       ['5.1', '3.5', '1.4', '.3', 'Setosa'],
       ['5.7', '3.8', '1.7', '.3', 'Setosa'],
       ['5.1', '3.8', '1.5', '.3', 'Setosa'],
       ['5.4', '3.4', '1.7', '.2', 'Setosa'],
       ['5.1', '3.7', '1.5', '.4', 'Setosa'],


`dtype='str'`로 지정해서 생성된 어레이의 항목 자료형이 `<U10`인 이유는
항목에 포함된 문자열 중에서 `'Versicolor'`의 길이가 10으로 가장 길기 때문이다.
아래 코드는 `iris_full_str`이 가리키는 어레이의 모양, 항목 자료형, 차원을 확인해준다.

In [15]:
print('모양:', iris_full_str.shape)
print('항목 자료형:', iris_full_str.dtype)
print('차원:', iris_full_str.ndim)

모양: (150, 5)
항목 자료형: <U10
차원: 2


### 연습 문제

(1) 특정 열을 1차원 어레이로 불러오기

`np.loadtxt()` 함수를 사용하여 붓꽃 데이터셋(`iris.csv`)에서 '꽃받침 너비(`sepal.width`)' 데이터만 포함된 1차원 어레이를 생성하라.
단, 헤더는 건너뛰고, 데이터 타입은 `float32`로 지정한다.
또한 생성된 어레이의 모양(`shape`)과 항목 자료형(`dtype`)을 출력하라.

답:

In [33]:
import numpy as np

data_url = 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

# 꽃받침 너비는 1번 열(인덱스 1)에 위치함
iris_sepal_width = np.loadtxt(data_url + "iris.csv", delimiter=',', skiprows=1, dtype='float32', usecols=1)

print("어레이 모양:", iris_sepal_width.shape)
print("항목 자료형:", iris_sepal_width.dtype)

어레이 모양: (150,)
항목 자료형: float32


설명:

꽃받침 너비 데이터는 CSV 파일의 두 번째 열에 있으므로 `usecols=1`을 지정한다.
첫 행은 헤더이므로 `skiprows=1`로 건너뛰고, `dtype='float32'`를 통해 32비트 부동소수점 자료형으로 데이터를 불러온다.

(2) 여러 열을 선택하여 2차원 어레이로 불러오기

붓꽃 데이터셋에서 '꽃잎 길이(petal.length)'와 '꽃잎 너비(petal.width)' 두 가지 특성만 추출하여 2차원 어레이를 생성하라.
생성된 어레이의 차원(`ndim`)과 모양(`shape`)을 확인하라.

답:

In [34]:
import numpy as np

# 꽃잎 길이(2번 열)와 꽃잎 너비(3번 열) 추출
iris_petal_features = np.loadtxt(data_url + "iris.csv", delimiter=',', skiprows=1, usecols=(2, 3))

print("어레이 차원:", iris_petal_features.ndim)
print("어레이 모양:", iris_petal_features.shape)

어레이 차원: 2
어레이 모양: (150, 2)


**설명:**
꽃잎 관련 데이터는 각각 2번, 3번 인덱스 열에 위치하므로 `usecols=(2, 3)` 튜플을 전달하여 두 열만 선택적으로 불러온다. 반환된 객체는 행과 열을 갖는 2차원 어레이(`ndim=2`)가 되며, 150개의 샘플과 2개의 특성을 가지므로 모양은 `(150, 2)`가 된다.

(3) 문자열 데이터와 숫자 데이터 함께 불러오기

붓꽃 데이터셋의 '꽃받침 길이(sepal.length)'(0번 열)와 '품종(variety)'(4번 열) 데이터를 함께 2차원 어레이로 불러오려 한다.
두 열을 함께 불러오는 코드를 작성하고, 생성된 어레이의 항목 자료형(`dtype`)이 어떻게 결정되는지 확인한 후 그 이유를 설명하라.

답:

In [35]:
import numpy as np

# 0번 열(숫자)과 4번 열(문자열)을 함께 불러오기
iris_mixed = np.loadtxt(data_url + "iris.csv", delimiter=',', skiprows=1, dtype='str', usecols=(0, 4))

print("항목 자료형:", iris_mixed.dtype)

항목 자료형: <U10


설명:

숫자형 데이터(꽃받침 길이)와 문자열 데이터(품종)를 하나의 넘파이 어레이로 불러오려면 
모든 항목이 동일한 자료형을 가져야 한다는 규칙 때문에 `dtype='str'`(또는 `object`)을 지정해야 한다. 
이 경우 숫자 데이터도 모두 문자열로 강제 변환되어 저장되며, `dtype`은 포함된 문자열 중 가장 긴 길이에 맞춰(예: `<U10`) 자동 지정된다.

(4) 데이터셋 크기 확인하기

데이터셋 크기는 데이터셋에 포함된 데이터 샘플의 수를 가리킨다.
`np.loadtxt()`를 이용해 붓꽃 데이터셋의 모든 수치형 특성(0번~3번 열)을 2차원 어레이로 불러온 후,
어레이의 속성을 이용하여 이 데이터셋에 총 몇 개의 붓꽃 샘플(행)이 포함되어 있는지 출력하는 코드를 작성하라.

답:

In [36]:
import numpy as np

# 수치형 특성 4개 불러오기
iris_numeric = np.loadtxt(data_url + "iris.csv", delimiter=',', skiprows=1, usecols=(0, 1, 2, 3))

# 샘플 수(행의 개수) 확인
num_samples = iris_numeric.shape[0]

print("어레이 모양:", iris_numeric.shape)
print("총 붓꽃 샘플 수:", num_samples)

어레이 모양: (150, 4)
총 붓꽃 샘플 수: 150


설명:

2차원 어레이의 `shape` 속성은 `(행의 개수, 열의 개수)` 형태의 튜플을 반환한다.
여기서 행의 개수(`shape[0]`)가 바로 데이터셋에 포함된 전체 샘플의 수를 의미한다.
튜플의 인덱싱은 리스트와 동일하게 작동하므로 `[0]`을 사용하여 첫 번째 항목을 가져올 수 있다.
붓꽃 데이터셋의 경우 150개의 샘플이 있으므로 150이 출력된다.