(ch:functions)=
# 함수

:::{seealso} 

1. 본문 코드 실행: [(Google Colab) 함수](https://colab.research.google.com/github/codingalzi/code-workout-python/blob/master/functions.ipynb)

2. 연습문제 해답과 해설: [(연습) 함수](https://colab.research.google.com/github/codingalzi/code-workout-python/blob/master/practices/practice-functions.ipynb)
:::

프로그램은 명령문의 조합으로 구현된다.
많은 프로그램은 수백, 수천 줄의 명령문으로 이루어지며,
경우에 따라 수십만, 수백만 줄, 심지어 천만 줄이 넘는 경우도 있다.

수십 줄 이상의 프로그램을 구현하다 보면
특정 기능을 수행하는 명령문을 반복해서 사용하게 된다.
또한 프로그램의 소스코드를 여러 파일로 나누어
작성하고 관리할 필요도 생긴다.
이때 함수와 모듈을 활용한다.

이 장에서는 먼저 함수를 살펴본다.

## 함수 호출과 표현식

**함수**<font size='2'>function</font>는 간단히 말해 특정 코드에 붙인 이름이다.
예를 들어 아래 코드를 실행하면 `"함수란 특정 명령문을 대신한다."` 라는 문장이 화면에 출력된다.

In [1]:
print('함수란', '특정 명령문을 대신한다.')

함수란 특정 명령문을 대신한다.


`print`는 실제로는 매우 복잡하게 작성된 코드를 나타내는 이름이다.
그 코드가 정확히 어떻게 구현되었는지 사용자는 쉽게 알 수 없으며, 또 굳이 알 필요도 없다. 
대신 화면에 문자열 등의 값을 출력하고 싶을 때 `print()` 함수를 사용한다는 사실만 알면 된다.
이처럼 함수의 용도를 알고 적절하게 활용하는 것이 가장 중요하다.

위 코드에서 `print()` 함수는 공백을 사이에 두고 주어진 두 개의 문자열 인자를 화면에 한 줄에 연속해서 출력한다.

### 함수 호출

함수는 아래 형식의 **함수 호출**<font size="2">function call</font> 명령문을
통해 활용된다.

```python
함수이름(인자1, 인자2, ..., 인자n)
```

함수 호출에 필요한 인자의 수는 함수의 정의에 의존한다.
예를 들어, `round()` 함수는 둘째 인자를 지정하지 않으면 소수점 이하를 버리고
정수를 계산한다.

In [1]:
round(3.141592)

3

둘째 인자를 0으로 지정하는 것과 결과가 동일하다.

In [15]:
round(3.141592, 0)

3.0

다만 두 함수호출 결과의 자료형이 서로 다르다.
이는 `round()` 함수가 그렇게 작동하도록 구현되었기 때문이며,
사용자는 이 점을 고려하면서 `round()` 함수를
어떤 방식으로 호출할지 정해야 한다.

In [17]:
type(round(3.141592))

int

In [18]:
type(round(3.141592, 0))

float

함수 호출에 요구되는 인자의 개수가 달라질 수 있다는 게 이상하게 보일 수 있지만
사실은 전혀 그렇지 않다.
이에 대해 키워드 인자를 소개하면서 보다 자세히 설명한다.

**인자 없는 함수 호출**

`print()` 함수처럼 특정 함수는 인자를 지정하지 않으면서 호출될 수도 있다.

In [1]:
print()

`print()` 함수를 인자없이 호출하면 아무런 결과가 없는 것처럼 보이지만
일단 오류가 발생하지 않은 점에 주목한다.
왜냐하면 어떤 함수는 인자 없이 호출되면 오류가 발생하기 때문이다.
예를 들어, 자료형을 확인해주는 `round()` 함수가 그렇다.

In [2]:
round()

TypeError: round() missing required argument 'number' (pos 1)

이유는 `round()` 함수는 `round(3.141592)` 또는 `round(3.141592, 2)` 처럼 소수점 이하 자릿수를 지정할 부동소수점이 필요한데 인자가 없으면 할 수 있는 일이 없기 때문이다.

결론적으로 다음 두 가지를 기억한다.

1. 함수 호출에 사용되는 인자의 개수는 함수의 정의에 의존한다.
1. 인자가 필요 없는 경우에도 `print()` 처럼 열고 닫는 소괄호를 반드시 사용해야 한다.

**값으로서의 함수**

함수를 소괄호 없이 코드에 사용할 수는 있으며, 절대 오류가 발생하지 않는다.
하지만 그것은 함수 호출이 아니라, 함수라는 값 자체를 가리킨다.
예를 들어 아래 코드의 실행결과에 주목한다.

In [28]:
x = print
x

<function print(*args, sep=' ', end='\n', file=None, flush=False)>

위 코드는 함수 자체를 하나의 값으로 취급하여 변수 할당에 활용하였다.
그리고 값을 확인할 때 `print`라는 (함수) 이름이 가리키는 값이 함수라는 사실과 함수의 인자로 사용될 수 있는 값들에 대한 정보, 
즉 함수 이름이라는 사실과 함수의 시그니처를 보여준다.

아래 코드에서처럼 `round` 라고 입력해도 동일하다.
즉, 소괄호 없이 함수 이름만 확인하는 일은 변수가 가리키는 값을 확인하는 것과 동일하다.
실제로 함수 이름 또한 변수처럼 취급된다.

In [4]:
round

<function round(number, ndigits=None)>

함수의 인자에 대한 보다 자세한 설명은 아래에서 자세히 다룬다.

### 함수 호출 표현식

함수 호출 표현식은 함수 호출 형식으로 값을 나타내는 표현식이다.
예를 들어 `round(3.141592, 2)`는 부동소수점 `3.14`를, 
`ord('A')`는 정수 `65`를 나타내는 표현식들이며,
따라서 변수 할당 등에 바로 활용될 수 있다.

In [9]:
pi = round(3.141592, 2)
print('원주율:', pi)

원주율: 3.14


In [10]:
unicode_A = ord('A')
print('A의 코드포인트:', unicode_A)

A의 코드포인트: 65


심지어 `type(3.14)`와 `type(65)`도 각각 부동소수점 3.14의 자료형인 `float`와
정수 `65`의 자료형인 `int`를 값으로 나타낸 함수 표현식이다.
파이썬 코드에서 다루는 모든 대상이 값인 이유가 여기에 있다.

In [13]:
type_of_pi = type(3.14)
print('3.14의 타입:', type_of_pi)

3.14의 타입: <class 'float'>


In [14]:
type_of_65 = type(65)
print('65의 타입:', type_of_65)

65의 타입: <class 'int'>


### 예제

**예제 1**

`ord()` 함수는 인자로 문자가 주어지면 해당 문자의 유니코드 코드 포인트를 반환한다.
영어 소문자 알파벳 `'a'`와 `'z'`의 유니코드 코드 포인트를 화면에 다음과 같이 출력하는 코드를 작성하라.

```python
a와 z의 코드포인트: 97 과 122
```

단, 두 변수 `code_point_a`, `code_point_z` 각각에 `'a'`와 `'z'`의 유니코드 코드 포인트를 할당한 후에 
`print()` 함수의 인자로 활용해야 한다.



답:

`code_point_a`와 `code_point_b` 두 변수 각각에 `ord()` 함수를 호출하여 반환된 값을 할당한 다음에
아래 코드에서처럼 `print()` 함수의 인자로 두 변수를 활용한다.

In [125]:
code_point_a = ord('a')
code_point_z = ord('z')
print('a와 z의 코드포인트:', code_point_a, '과', code_point_z)

a와 z의 코드포인트: 97 과 122


**예제 2**

`chr()` 함수는 유니코드 코드 포인트(정수)가 주어지면 그 숫자에 해당하는 문자를 반환한다. 
숫자 97, 98, 99를 `chr()` 함수의 인자로 사용할 때 어떤 문자들이 연속으로 출력되는지 확인하는 코드를 작성하라.

답:

97, 98, 99는 각각 영어 소문자 알파벳 `'a'`, `'b'`, `'c'`에 해당하는 유니코드 코드 포인트다.

In [127]:
print("97:", chr(97))
print("98:", chr(98))
print("99:", chr(99))

97: a
98: b
99: c


**예제 3**

`ord()` 함수가 반환하는 값은 단순한 정수이므로 숫자처럼 덧셈이나 곱셈에 활용할 수 있다.
알파벳 `'a'`와 `'b'`의 유니코드 코드 포인트 값을 서로 더한 결과가 어떤 문자의 코드 포인트와 같은지 `chr()` 함수를 사용해 확인하는 코드를 작성하라.

답:

97 + 98 = 195 이고, 
이는 라틴 확장 문자열 중 `Ã` (A with tilde) 에 해당한다.

In [ ]:
code_a = ord('a')
code_b = ord('b')
sum_code = code_a + code_b

print("두 문자의 코드를 더한 값:", sum_code)
print("해당 값의 유니코드 문자:", chr(sum_code))

두 문자의 코드를 더한 값: 195
해당 값의 유니코드 문자: Ã


**예제 4**

ROT13 은 영어 단어의 각 알파벳을 13 자리만큼 회전시키는 방식의 간단한 암호 작성 기법이다. 
알파벳을 회전시킨다는 것은 해당 알파벳을 지정된 수만큼 이동한 위치에 있는 알파벳으로 대치한다는 의미이며,
영어 알파벳이 총 26개이기에 알파벳 `'a'`부터 `'z'`까지 회전하면서 이동시킨다.
예를 들어, `'a'` 를 3만큼 이동하면 `'d'` 가, `'z'` 를 3만큼 이동하면 `'c'` 가 된다.
영어 소문자 알파벳이 주어졌을 때 ROT13 기법으로 암호화된 알파벳을 계산하는 코드를 작성하라.

힌트: `ord()` 함수와 `chr()` 함수를 이용한다.

**답**

주어진 영어 소문자 알파벳의 유니코드 코드 포인트에 13을 더한 값에 해당하는 문자를 구하면 된다.
그런데 영어 소문자 알파벳은 총 26개이기에 주어진 알파벳을 13 자리만큼 회전시키려면
`ord(char)` 값에 따라 다르게 계산해야 한다.
이를 위해 먼저 소문자 `'a'`와 `'z'`의 유니코드 코드 포인트를 확인한다.

In [117]:
ord('a')

97

In [118]:
ord('z')

122

영어 소문자의 유니코드 범위는 97(`'a'`)부터 122(`'z'`)다.
원래 문자의 유니코드 코드 포인트에 13만큼 더했을 때 소문자의 마지막인 `'z'`(122)를 넘어간다면, 
알파벳 전체 개수인 26을 빼주어 다시 맨 앞(`'a'`)으로 순환하도록 만들어 준다. 

- `ord(char) + 13 <= 122`인 경우: `ord(char)`에 13을 더해준 값에 해당하는 알파벳
- `ord(char) + 13 > 122`인 경우: `ord(char)`에 13을 더한 뒤 26을 뺀 (결과적으로 13을 빼준) 값에 해당하는 알파벳

아래 코드는 위 설명을 그대로 코드로 구현하여 `'a'`를 13자리만큼 이동시키면 `'n'`이 됨을 확인시켜준다.

In [59]:
char = 'a'

if ord(char) + 13 <= 122:
    encrypted = chr(ord(char) + 13)
else:
    encrypted = chr(ord(char) - 13)

print("원래 문자:", char)
print("암호화된 문자:", encrypted)

원래 문자: a
암호화된 문자: n


반면에 `'z'`를 13자리만큼 이동시키면 `'m'`이 된다.

In [60]:
char = 'z'

if ord(char) + 13 <= 122:
    encrypted = chr(ord(char) + 13)
else:
    encrypted = chr(ord(char) - 13)

print("원래 문자:", char)
print("암호화된 문자:", encrypted)

원래 문자: z
암호화된 문자: m


### 연습문제

**문제 1**

영어 알파벳에서 소문자와 대문자의 유니코드 코드 포인트(정수값) 차이는 항상 일정하게 유지된다.
이를 이용하여, 변수 `char_upper`에 할당된 대문자 `'A'`의 코드 포인트를 구한 후에
특정 숫자를 더해 소문자 `'a'` 로 변환시키는 코드를 작성하라. 

**문제 2**

영어 알파벳 `'a'`와 `'z'`의 유니코드 코드 포인트(정수값)의 평균을 구하면, 
알파벳 순서상 한가운데 위치한 문자가 무엇인지 수학적으로 알아낼 수 있다.
`ord()` 함수를 이용해 `'a'`와 `'z'`의 코드 포인트를 더한 뒤 2로 나눈 몫(정수 나눗셈 `//`)을 구하고, 
그 결과값을 `chr()` 함수에 전달하여 정중앙에 있는 문자를 확인하는 코드를 작성하라.

**문제 3**

ROT13 암호화를 영어 대문자 알파벳에 대해 작동하도록 구현한 다음에 대문자 알파벳 `'C'`와 `'P'`가 암호화된 알파펫을 확인하라.

힌트: 대문자 알파벳 `'A'`와 `'Z'`의 유니코드 코드 포인트를 확인한다.

## 사용자 정의 함수

지금까지 함수로 활용한 `print()`, `type()`, `round()` 등은 모두
파이썬이 기본으로 제공하는 **내장 함수**<font size='2'>built-in functions</font>이다.

그런데 수십 줄 이상의 코드를 작성하다 보면 특정 기능을 수행하는 코드를 반복해서 사용할 
필요가 발생하는데,
이런 경우 반복 사용되는 코드에 사용자가 직접 이름을 주어 함수로 정의하여
해당 코드가 필요할 때마다 정의된 함수를 대신 호출하면 된다.

함수는 아래 형식으로 정의된다.

```python
def 함수이름(매개변수1, 매개변수2, ...):
    함수본문 
```

### 함수 구성요소

**함수 시그니처**

`def` 키워드로 시작하는 줄은 함수의 이름과
함수를 호출할 때 사용하는 인자들에 대한 정보를 담으며,
보통 **함수 시그니처**<font size="2">function signature</font>
또는 **함수 헤더**<font size='2'>function header</font>라고 불린다.
함수 시그니처의 끝에는 콜론 기호(`:`)가 위치한다.

**함수 본문**

함수 시그니처 아래에 들여쓰기와 함께 작성된 코드는
함수의 **본문**<font size="2">body</font>이다.
함수의 본문은 함수가 호출되었을 때 실행되어야 하는 코드, 
즉 필요할 때마다 반복해서 사용하고 싶은 코드가 위치한다.

함수 본문은 사용되는 코드는 일정한 깊이로 들여써야 하며, 들여쓰기는 보통 <kbd>Tab</kbd> 키를 이용한다.
한 번의 탭 키 입력은 일반적으로 두 번 또는 네 번의 스페이스 키 입력에 해당하는데,
파이썬 편집기마다 조금씩 다르다.

**`return 표현식`과 함수 반환값**

함수 호출 명령문의 실행은 아래 두 가지 조건 중에 하나가 성립하면 종료된다.

1. 함수 본문을 실행하다가 `return 표현식` 명령문이 실행되는 순간
2. 함수의 본문 코드가 모두 실행 완료 되는 순간

함수가 호출되면 함수의 실행이 종료되어야 다음 명령문의 실행으로 이어진다.

함수 호출 명령문의 종료 조건으로 언급된 `return 표현식` 명령문은
함수의 반환값을 지정하며,
바로 그 반환값이 함수 호출 표현식이 표현하는 값이 된다.

이런 의미에서 함수 호출이 이뤄지면
어떠한 경우에도 두 개의 `return 표현식` 명령문이 실행되지 않는다.
그래야만 함수 호출 표현식이 표현하는 값이 유일하게 정해지기 때문이다.

하지만 그렇다혹 해서 함수 본문에 `return 표현식` 명령문이 한 번만 사용된다는 의미는 아니다.
예를 들어, 아래 `add_multiply()` 함수는 두 인자의 크기를 비교해서
첫째 인자가 크면 두 인자의 덧셈을, 그렇지 않으면 두 인자의 곱셈을 반환값으로 지정한다.

In [29]:
def add_multiply(left, right):
    if left < right:
        sum = left + right
        return sum
    else:
        product = left * right
        return product

두 인자의 크기에 따라 덧셈 또는 곱셈의 결과가 반환되지만
어떤 경우에도 `return sum` 과 `return product` 가 동시에 실행되지는 않는다.
바로 이런 의미에서 함수의 반환값은 항상 하나다.

아래 두 `add_multiply()` 함수 호출 예제에서 볼 수 있듯이 어떤 값이 반환될 것인가는
함수 정의 자체보다는 함수 호출에 사용된 인자들에 의해 정해진다.

- 첫째 인자가 둘째 인자보다 작을 때: 덧셈 실행

In [33]:
added = add_multiply(-2, 5)
print("add_multiply(-2, 5)이 표현하는 값:", added)

add_multiply(-2, 5)이 표현하는 값: 3


- 첫째 인자가 둘째 인자보다 클 때: 곱셈 실행

In [34]:
multiplied = add_multiply(5, -2)
print("add_multiply(5, -2)이 표현하는 값:", multiplied)

add_multiply(5, -2)이 표현하는 값: -10


**함수 이름과 매개변수 이름**

함수 정의에 사용되는 함수 이름과 매개변수의 개수와 각 매개변수의 이름은
구현되는 함수와 각 매개변수의 기능에 맞춰 사용자가 직접 정한다.
또한 함수 이름과 함께 매개변수 이름은 {numref}`%s절 <sec:naming>`에서 설명한
변수 이름 짓기와 동일한 조건을 따르면서 지정되어야 한다.

예를 들어, `add_multiply`라는 이름은 두 개의 값이 인자로 주어졌을 때 두 값을 더하거나 곱하는 기능과 연관된다.
또한 두 개의 수를 인자로 받아 합을 계산해야 하기에 두 개의 매개변수를 사용하고,
덧셈과 곱셈 모두 연산자 왼쪽과 오른쪽에 인자가 위치하기에 
두 매개변수의 이름을 `left`와 `right`로 지정하였다.

### 함수 인자 전달

함수의 **인자**<font size='2'>argument</font>는
함수 호출에 사용되는 값이다.

그리고 인자의 종류와 개수는 함수의 정의에 의존한다.
예를 들어, `added = add_multiply(-2, 5)` 변수 할당 명령문이 실행되면
`added` 변수에 할당할 값을 정하기 위해 먼저 `add_multiply(-2, 5)` 형식으로
`add_multiply()`함수가 `-2`와 `5` 두 인자와 함께 호출된다.

`add_multiply(-2, 5)` 형식으로 함수를 호출하면
`left < right` 판정 결과에 따라 덧셈 또는 곱셈을 실행한다.

그런데 `left < right`를 판정하기 위해서는 두 변수가 가리키는 값이
지정되어 있어야 한다.
따라서 함수 호출이 발생하면
파이썬 실행기는 함수의 본문을 실행하기 전에 먼저
모든 매개변수에 대한 변수할당을 주어진 인자들을 이용하여 실행한다.

함수가 호출되었을 때 파이썬 실행기 내부에서 실제로 실행되는 명령문은
두 단계로 나뉜다.

첫째, 매개변수 각각에 대해 주어진 인자의 순서대로 변수 할당 명령문이 실행된다.

```python
left = -2
right = 5
```

`left`와 `right` 두 매개변수가 함수의 본문에서 사용될 때 
이렇게 할당된 값을 이용한다.
이런 의미에서 '매개변수가 인자를 함수의 본문에 전달한다'고 말한다

둘째, `add_multiply()` 함수의 본문에 사용된 명령문이 차례대로 실행된다.

결국 `add_multiply(-2, 5)` 형식으로 함수 호출이 실행되면
아래 코드가 파이썬 실행기 내부에서 실행된다.

```python
left = -2
right = 5

if left < right:
    sum = left + right
    return sum
else:
    product = left * right
    return product
```

`add_multiply(-2, 5)` 함수 호출의 반환값은
`left < right` 여부에 따라 결정되는데,
이 경우엔 덧셈이 실행되어 아래 코드에 의해 3이 반환값으로 지정된다.

```python
sum = left + right
return sum
```

반환된 지정값은 애초에 실행된 변수 할당 명령문에 의해 
`added` 변수에 할당되어 계속해서 활용될 수 있게된다.

### 예제

**예제 1**

아래 코드는 `only_sum()` 함수를 정의한다.

In [ ]:
def only_sum(left, right):
    sum = left + right
    product = left * right
    return sum
    return product

아래 코드의 실행결과를 확인하고 그 이유를 설명하라.

In [ ]:
only_sum(-2, 5)

3

답:

`only_sum(-2, 5)`을 호출하면 먼저 아래 코드가 파이썬 실행기에 의해 실행된다.

In [ ]:
left = -2
right = 5
sum = left + right
product= left * right

따라서 `sum`과 `prod` 두 변수에 각각 2와 -10이 할당된다.
이제 아래 두 명령문을 실행할 차례다.

```python
return sum
return product
```

그리고 먼저 실행된 `return sum` 명령문에 의해 `sum`에 할당된 값이 반환값으로
지정되어 반환되면서 동시에 `only_sum(-2, 5)` 함수 호출이 종료되어
`return product` 는 아예 실행되지 않는다.
결국 `only_sum()` 함수는 다음과 같이 정의될 수 있다.
즉, `product` 변수의 정의와 반환값 지정은 필요 없다.

In [ ]:
def only_sum(left, right):
    sum = left + right
    return sum

**예제 2**

아래 코드를 실행할 때 발생하는 오류를 설명하라.

In [1]:
func_hi()

def func_hi() :
  print("Hi")

NameError: name 'func_hi' is not defined

**답**

파이썬 코드는 윗줄의 명령문부터 차례대로 실행된다.
`func_hi()` 함수가 정의되기 이전에 호출되면 해당 함수가 아직 정의되지 않았다는 의미의 `NameError` 오류가 발생한다.
이는 함수 호출 아랫쪽에 `func_hi()` 함수가 정의되어 있다 하더라도 마찬가지다.

**예제 3**

아래 코드는 소문자 알파벳 `'a'`를 13칸 이동시킨 결과를 확인해준다.

```python
char = 'a'

if ord(char) + 13 <= 122:
    encrypted = chr(ord(char) + 13)
else:
    encrypted = chr(ord(char) - tur13)

print("원래 문자:", char)
print("암호화된 문자:", encrypted)
```

위 코드의 일부를 이용해서 아래 기능을 갖는 `rot13()` 함수를 정의하라.

- `char`라는 매개변수 하나 사용
- 반환값은 인자로 사용된 소문자 알파벳을 13칸 이동시킨 위치의 소문자 알파벳

답:

함수를 정의하려면 함수의 시그니처와 반환값을 먼저 정해야 한다.
먼저 함수의 시그니처는 다음과 같아야 한다.

```python
def rot13(char):
```

함수 반환값은 13칸 이동한 위치의 소문자 알파벳이며,
위 코드에서 `encrypted` 변수에 가리키는 값이다.
따라서 반환값은 아래처럼 지정된다.

```python
return encrypted
```

본문의 나머지는 `char`를 이용해서 `encrypted`를 계산하는 과정으로 구성된다.
즉, 아래 과정이 함수 본문으로 사용된다.

```python
if ord(char) + 13 <= 122:
    encrypted = chr(ord(char) + 13)
else:
    encrypted = chr(ord(char) - tur13)

return encrypted
```

위 설명을 종합하여 `rot13()` 함수를 다음과 같이 정의한다.

In [62]:
def rot13(char):
    if ord(char) + 13 <= 122:
        encrypted = chr(ord(char) + 13)
    else:
        encrypted = chr(ord(char) - 13)
    
    return encrypted

이제 소문자 알파벳을 인자로 하여 `rot()` 함수를 호출해서 제대로 작동하는지 확인해 본다.

In [63]:
rot13('a')

'n'

In [64]:
rot13('n')

'a'

### 연습문제

**문제 1**

정수 `num`을 인자로 해서 호출되었을 때, 1의 자릿수가 3의 배수이면 입력값의 세 배를, 
아니면 두 배를 반환하는 함수 `three_or_not()` 함수를 구현하라.
매개변수는 `num` 하나만 사용한다.

힌트: `if ... else ...` 조건문과 나머지 연산자 `%` 활용

**문제 2**

짝수, 홀수 여부를 판정하는 함수를 활용하는 문제다.

(1) 정수 인자와 함께 호출되어 인자가 짝수일 때는 1, 홀수일 때는 0을 반환하는 함수 `even_odd()`를 구현하라.
매개변수는 `num` 하나만 사용한다.
단, 함수 본문에서 `return 표현식` 명령문은 한 번만 사용되어야 한다.

힌트: `if ... else ...` 조건문과 나머지 연산자 `%` 활용

(2) `even_odd()` 함수를 이용하여 인자가 짝수면 2로 나눈 몫을,
홀수이면 3배 더하기 1을 한 값을 반환하는 `mini_collatz()` 함수를 정의하라.
참고로 `collatz`는 콜라츠라고 읽으며,
콜라츠는 [콜라츠 추측](https://ko.wikipedia.org/wiki/%EC%BD%9C%EB%9D%BC%EC%B8%A0_%EC%B6%94%EC%B8%A1)이라는 
아직 미해결로 남아 있는 문제를 1937년에 제시한 독일 수학자 이름이다.

## `None` 반환값

아래 코드에 정의된 `double_int()` 함수의 정의는 `return ...` 명령문을 사용하지 않는다.
즉, 반환값을 지정하지 않는다.

In [1]:
def double_int(num_param):
    double_param = num_param * 2

그런데 아래 코드를 실행하면 `None` 이라는 이상한 값이 출력된다.

In [3]:
none_return = double_int(5)
print(none_return)

None


앞서 설명한 대로 `double_int(5)`가 호출되면
아래 코드가 실행된다.

```
num_param = 5
double_param = num_param * 2
```

위 코드가 실행되면 
`double_param` 변수에 10이 할당되는데 이후에 실행할 아무런 명령문이 없기에
반환값이 지정되지 않은 채 함수의 실행이 종료된다.

`none_return` 변수에는 원래 `double_int(5)`가 표현하는 값이
할당되어야 하는데 앞서 설명한 대로 반환값이 없다.
따라서 아무 것도 할당할 수 없어서 원래 오류가 발생해야 하지만,
파이썬 실행기는 이런 경우에 반환값을 `None`으로 강제 지정한다.
즉, `double_int()` 함수는 실제로는 
아래 코드처럼 정의된 것으로 간주된다.

In [35]:
def double_int(num_param):
    double_param = num_param * 2
    return None                   # None 반한값 지정

**None 값**

이상하게 들리겠지만 `None`은 '아무런 의미가 없음'을 의미하는 값이다.
아무런 의미가 없는 값이지만 그래도 하나의 값이라서 변수 할당에 사용될 수 있다.

In [6]:
non_value = None
print(non_value)

None


하지만 연산 등에는 활용될 수 없다.
아래 코드를 실행하면 허용되지 않은 자료형의 값을
연산에 사용했다는 의미의 `TypeError` 오류가 발생한다.

In [36]:
non_value + 1

NameError: name 'non_value' is not defined

:::{note} `None` 대 `0`

숫자 `0`은 '하나도 없다', '비어 있다' 등을 표현하는 값인 반면에
`None`은 아예 어떤 의미도 없음을 의미하는 값이다.
:::

**print() 함수의 반환값**

반환값이 `None`인 대표적인 함수가 `print()` 함수이다.
그런데 `print()` 함수를 아래와 같이 활용하면 마치 인자를 그대로 반환하는 것처럼 보인다.

In [29]:
print(3.14)

3.14


하지만 화면에 출력되는 `3.14`는 반환값이 아니다.
다만 `print()` 함수의 본문에 포함된 명령문 중에서
지정된 값을 화면에 출력하는 기능을 가진 어떤 명령문이 실행된 결과에 불과하다.
예를 들어, 아래 변수 할당 명령문을 실행하면 `3.14`가 화면에 출력된다.

In [9]:
print_return = print(3.14)

3.14


하지만 변수 할당 명령문은 등호 기호 오른편에 위치한 표현이 가리키는 값을
등호 기호 왼편에 위치한 변수가 가리키도록 하는 기능 이외에
아무 것도 하지 않는다.
그럼에도 불구하고 화면에 `3.14`가 출력되는 이유는
`print(3.14)` 함수 호출의 결과를 계산하는 과정에서
앞서 설명한 대로 인자로 지정된 `3.14`를 화면에 출력하기 때문이다.
반면에 `print(3.14)`를 실행한 뒤에 반환된 값은 `None`임을 아래 코드가 확인해준다.

In [10]:
print(print_return)

None


### 예제

**예제 1**

아래 코드의 실행 결과를 예측하고, 화면에 출력된 `result`의 값을 설명하라.

In [36]:
def show_multiply(a, b):
    product = a * b
    print("두 수의 곱:", product)

result = show_multiply(3, 4)
print("함수의 반환값:", result)

두 수의 곱: 12
함수의 반환값: None


답:

명령문은 윗줄부터 차례대로 실행된다.

- 먼저 변수 `result`에 값을 할당하기 위해 `show_multiply(3, 4)` 함수가 호출된다.
- 함수 본문이 실행되면서 `a * b`의 결과인 12가 계산되고, `print("두 수의 곱:", product)` 명령문에 의해 화면에 `두 수의 곱: 12`가 먼저 출력된다.
- 그다음, `show_multiply()` 함수에는 `return` 명령문을 통한 반환값 지정이 없기 때문에 파이썬 실행기는 강제로 `None`을 반환한다.
- 따라서 변수 `result`에는 `None`이 할당되고, 마지막 명령문에 의해 `함수의 반환값: None`이 출력된다.

**예제 2**

아래 코드의 실행 결과를 설명하라.
`func()` 함수는 인자를 사용하지 않음에 주의한다.

In [ ]:
print("A")

def func() :
    print("B")

print("C")

func()

A
C
B


**답**

파이썬 코드는 윗줄의 명령문부터 차례대로 실행되기에 아래 순서대로 명령문이 실행된다.

- `print("A")` 실행: `'A'` 출력
- `func()` 함수 정의
- `print("C")` 실행: `"C"` 출력
- `func()` 함수 호출: 인자 없이 함수 실행되어 함수 본문인 `print("B")` 실행. 따라서 `"B"` 출력

**예제 3**

아래 코드의 실행 결과를 설명하라.

In [147]:
x = print("A")

def func() :
    print("B")

y = func()

print(x == y)

A
B
True


**답**

윗줄의 명령문부터 차례대로 실행된다.

- `x = print("A")` 실행
    - 변수 `x`에 할당할 값을 정하기 위해 `print("A")` 호출
    - `print("A")` 호출 과정에서 `'A'`를 화면에 출력. 
    - 변수 `x`에 `print("A")`의 실행이 끝나면서 반환하는 값인 `None` 할당.
- `func()` 함수 정의
- `y = func()` 실행
    - 변수 `y`에 할당할 값을 정하기 위해 `func()` 호출
    - 함수 본문인 `print("B")` 실행 과정에서 `'B'`를 출력. 
    - 변수 `y`에 `func()` 호출의 실행이 끝나면서 반환하는 값인 `None` 할당.
- `print(x == y)` 실행
    - 변수 `x`와 변수 `y`가 가리키는 값이 모두 `None`임.
    - `None`이 의미 없는 값이지만 `None`과 `None`은 서로 동일한 값임.
    - 따라서 `x == y`는 `True`로 계산됨.
    - 화면에 `True` 출력

### 연습문제

**문제 1**

아래 코드를 실행하면 한 줄의 문자열이 정상적으로 출력된 후 오류가 발생한다.
화면에 출력되는 문자열이 무엇인지 확인하고, 오류가 발생하는 이유를 설명하라.

In [4]:
def double_number(n):
    result = n * 2
    print("두 배 계산 완료:", result)

value = double_number(5)
final_value = value + 10
print("최종 값:", final_value)

두 배 계산 완료: 10


TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**문제 2**

아래 코드의 실행 결과를 설명하라.

In [5]:
def funcA() :  
    print("A")

def funcB() :  
    print("B")
    funcA()   

funcB()

B
A


**문제 3**

아래 코드의 실행 결과를 설명하라.

In [6]:
print("Hi")   

def funcA() :  
    print("A")

def funcB() :  
    print("B")
    funcA()   

def funcC() :
    print("C")
    funcA()
    funcB()

print("D")
funcC()

Hi
D
C
A
B
A


(sec:keyword-arguments)=
## 위치 인자와 키워드 인자

함수의 인자는 **위치 인자**와 **키워드 인자** 두 종류로 구분된다.

- 위치 인자<font size="2">positional argument</font>: 함수를 호출할 때 반드시 순서에 맞게 지정되어야 하는 인자이다.
- 키워드 인자<font size="2">keyword argument</font>: 함수를 호출할 때 필요에 따라 추가로 지정될 수 있는 인자이다. 
    키워드 인자들 사이의 순서는 중요하지 않지만 반드시 위치 인자 다음에 자리해야 한다.

주어진 값을 위치 인자로 사용해야 할지 키워드 인자로 사용해야 할지는 
함수의 정의와 사용자의 의도에 의존한다.

`print()` 함수를 이용하여 위치 인자와 키워드 인자의 활용법을 소개한다.

### `print()` 함수의 인자

여러 개의 값을 화면에 출력하려면 `print()` 함수에 여러 개의 인자를 지정하여 호출한다.
그러면 인자들이 공백으로 구분되어 함께 한 줄에 출력된다.
예를 들어, 아래 코드는 `안녕`, `파이썬`, `!` 세 개의 문자열을 공백으로 구분하면서 한 줄에 출력한다.

In [12]:
print('파이썬', '안녕', '!')

파이썬 안녕 !


출력 대상으로 지정된 세 개의 인자가 공백으로 구분되어 한 줄에 출력되는 이유는
`sep`이라는 매개변수에 공백 문자 (`' '`)가 기본(defalut) 키워드 인자로 
약속되어 있기 때문이다.
위 코드를 실행하면 파이썬 실행기는 실제로는 아래 코드를 실행한다.

In [14]:
print('파이썬', '안녕', '!', sep=' ')

파이썬 안녕 !


변수 할당 명령문처럼 생긴 `sep=' '`은 화면에 출력해야할 인자들을 공백으로 구분하여 한 줄에 출력하도록
하는 기본 옵션 기능으로 작동한다.
함수 호출에 키워드 인자를 굳이 지정하지 않으면 
`sep=' '`처럼 기본 키워드 인자가 대신 사용된다.

함수를 활용할 때 숨겨진 키워드 인자들이 있는지를 미리 알고 있어야
제대로된 함수 호출 명령문을 작성할 수 있다.

**키워드 인자 변경**

키워드 인자에 할당된 값은 임의로 바꿀 수 있다.
예를 들어, 출력 대상으로 지정된 각각의 인자를 하이픈 기호`-`로 구분하려면
즉, 인자와 인자를 하이픈으로 연결하려면 
아래 코드에서처럼 `sep` 매개변수에 문자열 `-`을 키워드 인자로 지정하면 된다.

In [37]:
print('파이썬', '안녕', '!', sep='-')

파이썬-안녕-!


위 코드에서 `print()` 함수를 호출할 때 사용된 위치 인자와 키워드 인자는 다음과 같다.

- 위치 인자: 화면 출력에 사용되는 세 개의 인자, `'파이썬'`, `'안녕'`, `'!'`
- 키워드 인자: `sep` 매개변수에 할당된 문자열 `'-'`

**`print()` 함수의 키워드 인자**

`print()` 함수의 위치 인자는 0개 이상 원하는 만큼 사용할 수 있다.
반면에 키워드 인자는 `sep` 이외에 `end`, `file`, `flush` 매개변수에 할당될 수 있다.
실제로 `print()` 함수의 시그니처는 다음과 같다.

In [6]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

갹 매개변수의 역할은 다음과 같다.

:::{list-table} `print()`함수의 키워드 인자
:header-rows: 1
:name: print-keyword

*   - 매개변수
    - 기능
*   - `*args`
    - 별표 기호 (`*`)는 매개변수 `args`가 쉼표로 구분된 0개 이상의 (위치) 인자를 받을 수 있음을 표시
*   - `sep=' '`
    - 위치 인자로 지정된 여러 개의 값을 구분하는 문자열 구분자 지정. 기본 키워드 인자는 공백 문자
*   - `end='\n'`
    - 위치 인자를 모두 출력한 후에 출력하는 문자열 지정. 기본 키워드 인자는 줄바꿈 문자
*   - `file=sys.stdout`
    - 화면 출력 방식 지정. 기본 키워드 인자는 코드가 실행된 화면에 출력하는 표준 출력
*   - `flush=False`
    - 플러시 기능 사용 여부 지정. 기본 키워드 인자는 `False`
:::

각 키워드 인자는 고유의 기능을 수행하며, 
지정된 키워드 인자를 사용할 경우 함수 호출 과정에서 
해당 키워드 인자를 굳이 언급할 필요가 없다.
예를 들어, `end` 매개변수의 기본 키워드 인자가 줄바꿈이기에 `print()` 함수를 호출한 다음엔 항상 줄바꿈이 실행된다.
만약에 빈 문자열 `''`을 `end` 매개변수에 할당하면 줄바꿈을 하지 않는다. 
아래 두 코드를 비교하면 `end` 매개변수에 할당되는 키워드 인자의 역할을 확인할 수 있다.

- 기본 키워드 인자를 그대로 사용한 경우: 첫째 `print()` 함수 호출에 의해 `'파이썬 안녕 !'`이 출력된 후에
    줄바꿈이 이뤄지고 그 다음에 둘째 `print()` 함수 호출에 의해 `'==='` 문자열이 출력됨.

In [7]:
print('파이썬', '안녕', '!')
print('줄바꿈 후 현재 문장 출력.')

파이썬 안녕 !
줄바꿈 후 현재 문장 출력.


- `end` 매개변수의 인자를 빈 문자열로 지정한 경우: 첫째 `print()` 함수 호출에 의해 `'파이썬 안녕 !'`이 출력된 후에
    줄바꿈을 하지 않은 채로 둘째 `print()` 함수 호출에 의해 `'==='` 문자열이 출력됨.

In [8]:
print('파이썬', '안녕', '!', end='')
print('줄바꿈 없이 현재 문장 출력.')

파이썬 안녕 !줄바꿈 없이 현재 문장 출력.


:::{note}

`print()` 함수의 `file`과 `flush` 두 매개변수는 특별한 경우에 활용되며 여기서는 다루지 않는다.
관심이 있는 경우 [print() 함수의 키워드 인자 기능](https://velog.io/@janeljs/python-print-sep-end-file-flush)에서 
활용 에제를 확인할 수 있다.
:::

### 키워드 인자 사용 함수 정의

아래 `four_basic_operations()` 함수는 두 개의 정수 또는 부동소수점이 주어졌을 때 셋째 인자로 주어진 문자열에 따라
사칙연산 중의 하나를 실행해서 계산된 값을 반환한다.

In [38]:
def four_basic_operations(left, right, op=None):
    if op == "sum":
        result = left + right
    elif op == "difference":
        result = left - right
    elif op == "product":
        result = left * right
    elif op == "quotient":
        result = left / right
    else:
        result = None
    return result    

위 함수 정의에 사용된 매개변수 세 개의 역할은 다음과 같다.

- `left`: 연산의 왼쪽 값으로 사용될 값을 위치 인자로 할당받을 매개변수
- `right`: 연산의 오른쪽 값으로 사용될 값을 위치 인자로 할당받을 매개변수.
- `op`: 연산자를 지정하는 문자열. 기본 인자로 `None` 지정.

함수 본문은 `op` 매개변수에 대해 지정되는 키워드 인자에 따라
`left`와 `right` 두 개의 키워드 인자에 대한 연산을 실행하고
그 결과를 반환한다.

| `op` 키워드 인자    | 수행 연산 |
|---------------|-----------|
| `op="sum"`        | 덧셈 |
| `op="difference"` | 뺄셈 |
| `op="product"`    | 곱셈 |
| `op="quotient"`   | 나눗셈 |
| 기타 | 연산 없음 |

아래 코드에서처럼 `four_basic_operations()` 함수를 호출할 때 셋째 인자가 생략되면 
자동으로 `None`이 `op` 매개변수의 키워드 인자로 지정된다.
따라서 함수 본문의 `if` 조건문에서 `else` 부분의 명령문 실행되어 `result` 변수에 
`None`이 할당된다.
결국 `None`이라는 쓸모 없는 값을 반환하게 되어 아래 코드를 실행해도 아무 것도 얻지 못한다.

In [39]:
four_basic_operations(5, 3)

위 코드를 실행할 때 파이썬 실행기는 실제로는 아래 코드를 실행한다.

In [40]:
four_basic_operations(5, 3, op=None)

`None` 대신 적절할 문자열을 `op` 매개변수의 키워드 인자로 지정하면
적절한 연산 결과가 반환된다.
예를 들어, 아래 코드는 5 더하기 3, 즉 8을 반환한다.

In [41]:
four_basic_operations(5, 3, op='sum')

8

반면에 아래 코드는 7 나누기 2의 결과는 3.5를 반환한다.

In [42]:
four_basic_operations(7, 2, op='quotient')

3.5

### 키워드 인자 위치와 순서

아래 두 코드는 동일한 결과를 낳는다.

In [54]:
print('파이썬', '안녕', '!', sep='-', end='')
print('줄바꿈 없이 현재 문장 출력.')

파이썬-안녕-!줄바꿈 없이 현재 문장 출력.


In [56]:
print('파이썬', '안녕', '!', end='', sep='-')
print('줄바꿈 없이 현재 문장 출력.')

파이썬-안녕-!줄바꿈 없이 현재 문장 출력.


이유는 키워드 인자들은 작성 순서와 상관없이 할당되어지는 매개변수가 함께 지정되기 때문이다.
반면에 아래 두 코드는 결과가 다르다.

In [ ]:
print('파이썬', '안녕', '!', sep='-', end='')
print('줄바꿈 없이 현재 문장 출력.')

파이썬-안녕-!줄바꿈 없이 현재 문장 출력.


In [57]:
print('안녕', '파이썬', '!', end='', sep='-')
print('줄바꿈 없이 현재 문장 출력.')

안녕-파이썬-!줄바꿈 없이 현재 문장 출력.


이유는 위치 인자들의 순서를 바꾸면 값이 할당되는 매개변수가 달라지기 때문이다.
결국 인자들의 순서가 절대적으로 중요한데, 키워드 인자들의 경우엔 매개변수를 함께 작성하기 때문에 언급되는 순서가 전혀 중요하지 않다.

단, 키워드 인자는 반드시 위치 인자들보다 나중에 위치해야 한다.
그렇지 않으면 아래 코드에서처럼 함수 호출 형식이 틀렸다는 의미의 `SyntaxError` 오류가 발생한다.

In [43]:
print('파이썬', '!', sep='-', '안녕', end='')
print('줄바꿈 없이 현재 문장 출력.')

SyntaxError: positional argument follows keyword argument (505063070.py, line 1)

### 예제

**예제 1**

`round()` 함수의 매개변수 `ndigits`를 이용하여 아래 부동소수점을 소수점 이하 입곱째 자리에서 반올림하라.

```python
pi = 3.141592653589793
```

답:

`round()` 함수의 시그니처를 확인하면 함수 정의에 사용된 매개변수들을 확인할 수 있다.
함수의 시그니처는 함수 이름만으로 확인된다.

In [17]:
round

<function round(number, ndigits=None)>

시그니처에 따르면 `round()` 함수는 `number`, `ndigits` 두 개의 매개변수를 사용하는데
그중에 `ndigits` 매개변수에 키워드 인자를 지정할 수 있다.
기본 키워드 인자는 `None`이며, 이는 반환값으로 소수점 이하를 버린 부동소수점으로 지정한다.
반면에 `ndigits=6`으로 지정하면 소수점 이하 일곱째 자리에서 반올림한 부동소수점을 반환한다.

In [20]:
pi = 3.141592653589793

result = round(pi, ndigits=6)
print("일곱째 자리에서의 반올림 결과:", result)

일곱째 자리에서의 반올림 결과: 3.141593


**예제 2**

함수 호출에 사용되는 인자들이 함수 정의에 사용된 매개변수들의 순서에 맞게 사용된다면 키워드 인자들을 매개변수를 언급하지 않으면서 사용해도 된다.
예를 들어 아래 두 코드는 파이썬 실행기에 의해 동일하게 처리된다.

In [64]:
four_basic_operations(10, 5, op='difference')

5

In [63]:
four_basic_operations(10, 5, 'difference')

5

반면에 `print()` 함수의 경우는 키워드 인자를 사용할 때 매개변수를 반드시 언급해야 함을 확인해준다.
두 코드의 결과가 다른 이유를 설명하라.

In [66]:
print('파이썬', '안녕', '!', sep='---')

파이썬---안녕---!


In [67]:
print('파이썬', '안녕', '!', '---')

파이썬 안녕 ! ---


답:

`print()` 함수를 호출할 때 사용할 수 있는 키워드 인자의 개수가 함수를 정의할 때 정해지지 않았기 때문이다.
따라서 둘째 코드는 네 개의 인자 모두를 키워드 인자로 처리하며, `sep` 매개변수에 대한 인자는 기본값은 공백을 사용한다.

**예제 3**

아래 `rot13()` 함수는 ROT13 암호 기법을 실행한다.

```python
def rot13(char):
    if ord(char) + 13 <= 122:
        encrypted = chr(ord(char) + 13)
    else:
        encrypted = chr(ord(char) - 13)
    
    return encrypted
```

칸 이동을 13 뿐만 아니라 임의의 수만큼 진행하는 암호화 기법을 실행하는 `rot()` 함수를 구현하라.

- 두 개의 매개변수 `char`와 `turn` 사용
- `char`는 영어 대문자 알파벳을 위치 인자로 받고, `turn`은 칸의 이동 횟수를 키워드 인자로 받음. 기본 키워드 인자는 13. 단, `turn`이 1보다 작거나 25보다 크면 칸 이동을 하지 않아야 함.
- 반환값은 `encrypted` 변수가 가리키는 값. 인자로 지정된 대문자 알파벳을 `turn`만큼 이동시켰을 때의 알파벳을 가리켜야 함.

답:

기존 `rot13()` 함수는 이동하는 칸 수가 13으로 고정되어 있었지만, 이를 키워드 인자를 통해 임의의 수(기본값 13)만큼 이동할 수 있도록 일반화하는 
아래 모양의 시그니처를 가져야 한다.

```python
def rot(char, turn=13):
```

반환값은 `rot13()` 경우와 동일하게 암호화된 알파벳을 가리키는 `encrypted` 변수로 지정한다.
다만 `encrypted` 변수의 정의를 정수 13이 아닌 `turn` 변수를 이용해야 한다.

먼저 `1 <= turn <= 25`이 성립하지 않으면 바로 `char`을 반환하도록 한다.
그리고 해당 조건이 성립하면 아래 내용을 참고해서 함수를 작성한다.

- 영어 대문자의 유니코드 범위는 65(`'A'`)부터 90(`'Z'`)까지다.
- 원래 문자의 유니코드 포인트에 `turn`만큼 더했을 때 90을 넘어간다면, 
    알파벳 전체 개수인 26을 빼주어 다시 맨 앞(A)으로 순환하도록 만들어 줄 수 있다.

위 설명을 이용하여 `rot()` 함수를 다음과 같이 정의할 수 있다.

In [ ]:
def rot(char, turn=13):
    # turn이 1 이상 25 이하가 아닐 때는 바로 원래 문자를 반환
    if not (1 <= turn <= 25):
        return char

    # 문자를 이동시켰을 때 Z(90)를 넘어가는지 확인
    if ord(char) + turn <= 90:
        encrypted = chr(ord(char) + turn)
    else:
        # Z를 넘어가면 26을 빼서 다시 앞부분순서로 돌아가게 함
        encrypted = chr(ord(char) + turn - 26)
        
    return encrypted

둘째 인자, 즉 키워드 인자를 지정하지 않으면 `turn`이 13을 가리키게 되어 `rot13()` 함수와 동일하게 작동한다.

In [3]:
print("A를 기본값 13만큼 이동:", rot('A'))           # A -> N
print("U를 기본값 13만큼 이동:", rot('U'))           # U -> H

A를 기본값 13만큼 이동: N
U를 기본값 13만큼 이동: H


`turn` 매개변수의 키워드 인자를 다르게 지정하면 ROT13 기법과 다른 암호화 기법이 적용된다.

In [4]:
print("A를 3만큼 이동:", rot('A', turn=3))          # A -> D
print("U를 7만큼 이동:", rot('U', turn=7))          # U -> B

A를 3만큼 이동: D
U를 7만큼 이동: B


`turn`이 1보다 작거나 25보다 크면 암호화가 진행되지 않는다.

In [5]:
print("A 미이동:", rot('A', turn=0))               # A -> A
print("U 미이동:", rot('U', turn=27))              # U -> U

A 미이동: A
U 미이동: U


### 연습문제

**문제 1**

문자열과 양의 정수를 인자로 받아, 문자열을 정수만큼 반복 출력하는 함수
`text_copy_2or3()`를 구현하려 한다.
단, 매개변수는 다음 두 개를 사용하며, 시그니처는 다음과 같아야 한다.

```python
def text_copy_2or3(text, count=1):
```

- `text`: 첫째 인자. 문자열을 인자로 사용.
- `count`: 둘째 인자. 양의 정수를 인자로 사용. 기본 키워드 인자로 1 지정.
    0이하의 정수이면 `text` 인자를 그대로 화면에 출력해야 함.

예를 들어 `text_copy_2or3("Hello ", 3)`를 실행하면 다음처럼 출력돼야 한다.

```
Hello Hello Hello 
```

반면에 `text_copy_2or3("Hello ")`를 실행하면 다음처럼 출력돼야 한다.

```
Hello 
```

힌트: `print()` 함수 활용

**문제 2**

문자열 또는 리스트 포함된 항목을 인덱싱으로 확인할 수 있다.
예를 들어 `'python'` 문자열의 0번 인덱스의 문자는 `'p'`이고,
`[1, 3, 5, 7, 9]` 리스트의 -2번 인덱스의 항목은 `7`이다.

In [17]:
language = 'python'
odd_upto_10 = [1, 3, 5, 7, 9]

print('python 문자열의 0번 인덱스 항목:', language[0])
print('홀수 리스트의 뒤에서 2번째 항목:', odd_upto_10[-2])

python 문자열의 0번 인덱스 항목: p
홀수 리스트의 뒤에서 2번째 항목: 7


문자열 또는 리스트의 길이가 n일 때 인덱스로 허용되는 정수의 범위는 아래와 같다.

- 양의 정수 인덱스: 0부터 (n-1) 까지의 양의 정수
- 음의 정수 인덱스: -1부터 -n 까지의 음의 정수

즉, 아래 범위에 포함된 정수들만 인덱스로 사용 가능하다.

```python
-n <= 정수인덱스 < n
```

언급된 범위를 범위를 벗어나는 인덱스를 사용하면 오류가 발생한다.

예를 들어, 아래 두 코드는 허용 범위를 벗어난 정수를 인덱스로 사용하면
오류가 발생함을 보여준다.

In [18]:
language[6]

IndexError: string index out of range

In [19]:
odd_upto_10[-8]

IndexError: list index out of range

문자열 또는 리스트의 인덱싱과 동일한 기능을 지원하지만 허용된 범위의 인덱스가 아닐 때
오류를 발생시키는 대신 지정된 값을 반환하는 
`getitem()` 함수를 정의하라.
단, 함수 시그니처는 다음과 같아야 한다.

```python
def getitem(str_or_list, idx, default=None):
```

- `str_or_list`: 문자열 또는 리스트를 받는 매개변수
- `idx`: 인덱스를 받는 매개변수
- `default=None`: `idx`가 허용된 범위를 벗어날 때 오류를 발생시키는 대신 사용되는 반환값 지정. 기본 키워드 인자는 `None`

## 지역 변수와 전역 변수

코드에 사용되는 변수를 크게 지역 변수와 전역 변수로 구분한다.
설명을 위해 아래 `exponentiation()` 함수를 이용한다.
`exponentiation()` 함수는 위치 인자와 키워드 인자를 각각 하나씩 받아서
위치인자를 키워드 인자만큼 거듭제곱한다.

In [47]:
def exponentiation(number, power=2):
    power_result = number ** power
    return power_result

`power` 매개변수의 기본 키워드 인자가 2이기에 둘째 인자를 지정하지 않은 채로 `exponentiation()` 함수를 호출하면
지정된 인자의 제곱이 반환된다.

In [48]:
seventeen = 17
squared = exponentiation(seventeen)
print('17의 제곱:', squared)

17의 제곱: 289


제곱 대신 세제곱을 계산하려면 `power=3` 방식으로 키워드 인자를 변경해서 함수를 호출해야 한다.

In [49]:
twelve = 12
cubed = exponentiation(twelve, power=3)
print('12의 세제곱:', cubed)

12의 세제곱: 1728


### 지역 변수

`exponentiation()` 함수의 두 매개변수 `number`와 `power`, 그리고 함수 본문에서 정의된 `power_result` 세 변수는
`exponentiation()` 함수와 독립적으로 존재하지 않으며,
아래와 같이 변수들을 확인하려 하면 `NameError` 오류가 발생한다.

In [50]:
print(number)

NameError: name 'number' is not defined

In [51]:
print(power)

NameError: name 'power' is not defined

이는 함수가 호출되어 실행이 완료된 이후에도 마찬가지다.

In [52]:
exponentiation(5, power=3)

125

In [53]:
print(power)

NameError: name 'power' is not defined

In [54]:
print(power_result)

NameError: name 'power_result' is not defined

이유는 함수 정의에 사용된 매개변수와 
함수 본문에서 정의된 변수는
함수의 본문이 실행되는 도중에는 존재 의미를 갖지만
함수의 실행이 종료되는 순간 컴퓨터(메모리)에서 삭제되어 더 이상
존재하지 않게 되기 때문이다.

함수의 매개변수 또는 함수 본문에서 정의된 변수처럼 특정 코드의 실행시간동안만
의미를 갖는 변수를 
**지역 변수**<font size='2'>local variable</font>라 부른다.

:::{note} 함수 반환값 지정 기준

함수 호출 과정에서 계산된 값 또는 지역 변수에 할당된 값을 
함수 호출이 끝난 후에도 활용할 수 있는 방법은
그 값을 반환값으로 지정하는 것 외엔 없다.
즉, 함수의 반환값은 함수 외부에서 활용하고자 계산된 값이라고
말할 수 있다.
:::

### 전역 변수

함수 외부에서 정의된 변수는 언제든지 코드에서 활용할 수 있다.
예를 들어, `seventeen`와 `twelve` 변수가 그렇다.

In [55]:
print("seventeen 변수:", seventeen)

seventeen 변수: 17


이처럼 언제나 활용할 수 있는 변수를 **전역 변수**<font size="2">global variable</font>라 부른다.

**변수 종류에 따른 이름 구분**

지역 변수와 전역 변수의 이름은 구분해서 작성하는 게 좋다.
그렇지 않으면 아래 코드가 보여주듯이 혼란스러워질 수 있다.

아래 코드에서 `power` 가 전역 변수와 지역 변수로 사용된다.
하지만 두 변수는 서로 전혀 상관이 없다.

In [50]:
power = 3

print("2의 네제곱:", exponentiation(2, power=4))
print("power =", power)

2의 네제곱: 16
power = 3


위 코드 마지막 줄의 함수 호출 `print("power =", power)`에서의 `power` 변수는 첫째줄에서 정의된 전역 변수 `power`에 할당된 3을 가리킨다.
반면에 `exponentiation(2, power=4)` 함수의 매개변수로 사용된 지역 변수 `power`는 함수가 호출되어 실행되는 과정동안 4를 가리키지만
함수의 실행이 완료되고, 다음 명령문으로 넘어가는 순간 존재 자체가 사라진다.

반면에 매개변수가 함수가 실행되는 동안은 살아있다는 사실은 
아래 코드에서처럼 함수 본문에 `print()` 함수를 추가해서 확인할 수 있다.

In [68]:
power = 3

def exponentiation(number, power=2):
    print("power (지역 변수) =", power)
    power_result = number ** power
    return power_result

quadruple_of_two = exponentiation(2, power=4)
print("power (전역  변수)=", power)

power (지역 변수) = 4
power (전역  변수)= 3


:::{note}

함수 본문에 `print()` 함수를 추가해서 함수 실행 과정동안의 값의 변화를 확인하는 방식은
작성된 코드를 검증하거나 버그를 찾아내는 디버깅 과정에서
유용하게 활용되는 가장 기본적인 기법이다.
:::

동일한 이름을 지역 변수와 전역 변수에 사용함으로써 발생할 수 있는 혼란을 방지하기 위해
아래 코등처럼 서로 다른 이름을 사용할 것을 권장한다.

In [69]:
power_global = 3

def exponentiation(number, power=2):
    print("power (지역 변수) =", power)
    power_result = number ** power
    return power_result

quadruple_of_two = exponentiation(2, power=4)
print("power_global (전역 변수) =", power_global)

power (지역 변수) = 4
power_global (전역 변수) = 3


### 예제

**예제 1**

아래 코드는 전역 변수 `multiplier`의 값을 `multiply()` 함수 내부에서 사용하려 시도한다. 
코드를 실행했을 때 어떤 결과가 나오는지 설명하고, 그 이유를 변수 탐색 원리에 기반하여 설명하라.

In [95]:
multiplier = 5

def multiply(number):
    return number * multiplier

print("10 곱하기 5 =", multiply(10))

10 곱하기 5 = 50


답:

파이썬은 함수 내부에서 변수를 사용할 때 지역 변수에서 먼저 찾고, 없으면 함수 외부의 전역 변수에서 찾는다.
위 코드에서 `multiplier`는 함수 내부에 할당된 적이 없으므로 외부의 전역 변수 5를 가져와서 사용한다.
따라서 오류 없이 `50`이 정상적으로 반환되어 화면에 출력된다.

**예제 2**

아래 코드는 함수 내부와 외부에 동일한 이름의 변수 `message`를 사용한다.
코드를 실행했을 때의 출력 결과를 예측하고, 왜 그렇게 출력되는지 지역 변수와 전역 변수의 특징을 이용해 설명하라.

In [96]:
message = "전역 변수-안녕하세요"

def say_message():
    message = "지역 변수-반갑습니다"
    print("함수 내부 출력:", message)

say_message()
print("함수 외부 출력:", message)

함수 내부 출력: 지역 변수-반갑습니다
함수 외부 출력: 전역 변수-안녕하세요


답:

함수 내부에서 변수에 값을 할당하면, 함수 외부에 동일한 이름의 변수가 있더라도 덮어쓰지 않고 새로운 '지역 변수'가 만들어진다.
지역 변수는 함수가 종료되면 메모리에서 사라지므로, 외부의 전역 변수에는 아무런 영향을 주지 않는다. 
따라서 결과는 다음과 같이 출력된다.

```python
함수 내부 출력: 지역 변수-반갑습니다
함수 외부 출력: 전역 변수-안녕하세요
```

**예제 3**

지역 변수와 전역 변수에 대한 이해를 바탕으로, 아래 코드를 실행할 때 발생하는 오류의 원인을 설명하라.
또한 매개변수와 반환값을 활용하여 전역 변수 `count`가 1 증가한 값으로 안전하게 갱신되도록 코드를 수정하라.

In [97]:
count = 0

def increment():
    count = count + 1
    return count

print("증가된 값:", increment())

UnboundLocalError: cannot access local variable 'count' where it is not associated with a value

답:

함수 내부에서 할당 연산자(`=`)를 사용하면 파이썬은 해당 변수를 지역 변수로 처리한다.
즉 `count = count + 1`을 실행할 때, 오른쪽의 `count`는 전역 변수가 아닌 아직 값이 정해지지 않은 지역 변수로 취급되므로 값이 없다는 오류(`UnboundLocalError`)가 발생한다. 

전역 변수를 직접 함수 안에서 수정하려 하기보다, 아래와 같이 함수가 인자로 값을 전달받아 계산한 뒤 반환하는 형태로 수정해 사용하는 것이 바람직하다.

In [98]:
count = 0

def increment(current_count):
    new_count = current_count + 1
    return new_count

count = increment(count)
print("증가된 값:", count)

증가된 값: 1


### 연습문제 

**문제 1**

아래 코드를 실행할 때 발생하는 오류를 설명하라.

In [99]:
def square_return(number):
    square = number ** 2
    return square

number = 17
square17 = square_return(number)

print(number, "의 제곱을 계산한", square17, "과", square, "는 동일한 값을 가리킨다.")

NameError: name 'square' is not defined

**문제 2**

다음 코드를 실행한 후 화면에 출력되는 `a`와 `b`의 값을 예측하고, 
그렇게 출력되는 이유를 매개변수와 지역 변수의 특징에 기반하여 설명하라.

In [100]:
a = 10
b = 20

def swap(a, b):
    temp = a
    a = b
    b = temp
    return a, b

swap(30, 40)
print("a =", a)
print("b =", b)

a = 10
b = 20


**문제 3**

아래 `add_item()` 함수는 장바구니 역할을 하는 리스트 전역 변수 `cart`에 새로운 물건을 추가하려고 작성되었다. 
하지만 코드를 실행하면 오류가 발생한다.

In [102]:
cart = ["사과", "우유"]

def add_item(item):
    cart = cart + [item]

add_item("파이썬 책")
print("현재 장바구니:", cart)

UnboundLocalError: cannot access local variable 'cart' where it is not associated with a value

발생하는 오류의 원인을 설명하고, 매개변수와 반환값을 활용하는 방식으로 코드를 정상 작동하도록 수정하라.
단, 새로운 함수의 시그니처는 다음과 같아야 한다.

```python
def add_item(current_cart, item):
```

## `input()` 함수

지금까지는 변수에 담을 값이나 함수에 전달할 인자를 코드 안에 직접 지정했다.
하지만 프로그램이 실행되는 도중에 사용자로부터 원하는 값을 직접 입력받으려면 어떻게 해야 할까?
이제 앞서 배운 내용을 바탕으로 사용자와 상호작용하는 간단한 프로그램을 만들어 보자.
파이썬에서 키보드를 통해 데이터를 직접 입력받을 때는 내장 함수인 `input()`을 사용한다.

아래 코드를 실행한 다음에 키보드에서 숫자 13을 입력하고 <kbd>Enter</kbd> 키를 누르면 
최종적으로 `'맞았습니다!'`가 출력된다.

In [104]:
print("숫자맞히기 게임에 환영합니다.")

secret = 13
guess_str = input("10부터 19 사이의 숫자 하나를 입력하세요: ") 
print("입력한 값:", guess_str)
guess = int(guess_str)

if secret == guess:
    print("맞았습니다!")
else:
    print("틀렸습니다!")

숫자맞히기 게임에 환영합니다.
입력한 값: 13
맞았습니다!


위 코드의 실행 내용은 다음과 같다.

- 첫째줄의 `print()` 함수 호출이 실행되어 환영인사를 출력한다.
- `secret` 변수에 정수 13을 할당한다.
- `input()` 함수가 호출되면 사용자가 무언가를 입력할 때까지 기다리고, 1, 3과 엔터 기호를 입력하면 다음 명령문을 실행한다.
- 사용자가 입력한 1과 3은 `input()` 함수에 의해 문자열 `'13'`으로 반환되어 변수 `guess_str`에 할당된다.
- 할당된 값을 화면에 출력한다.
- 문자열 `'13'`이 곧바로 `guess` 변수에 정수 13으로 변환되어 할당된다.
- `secret == guess`가 `True`로 계산되어 "맞았습니다!"가 화면에 출력된다.

### `input()` 함수 사용법

일반적인 `input()`의 사용법은 다음과 같다.

```python
input("입력값 안내 문구")
```

**`input()` 함수 인자**

`input()` 함수와 함께 지정되는 문자열 인자는 
사용자가 입력해야 하는 값에 대한 정보를 알려주는 문구이며,
사용자rk 입력한 값에는 어떠한 영향도 미치지 않는다.

:::{note}

`input()` 함수의 시그니처를 확인하면
`prompt`라는 매개변수에 빈 문자열이 기본 키워드 인자로 지정되어 있다.

```python
Signature: input(prompt='')
...
```

지금까지 설명된 키워드 인자의 사용법에 따르면
`input()` 함수를 다음과 같이 호출해야 한다.

```python
input(promt="입력값 안내 문자열")
```

하지만 위치 인자 없이 하나의 키워드 인자만 사용하기에 굳이 키워드 인자를 받는 매개변수를 언급하지 않아도 자동으로 `prompt` 변수의 키워드 인자로 지정된다.
:::

입력값 안내 문자열을 지정하지 않으면 `prompt=''` 인자가 적용되어
아무런 정보가 보여지지 않은 상태에서 사용자가 <kbd>Enter</kbd> 키를 입력할 때까지 
코드의 실행이 정지된다.

예를 들어, 아래 코드를 실행하고 `파이썬`을 입력한 후에 <kbd>Enter</kbd> 키를 누르면
그제서야 입력된 문자열 `'파이썬'`이 그대로 반환값으로 지정되고
`print()` 함수가 그 반환값을 인자로 받아 화면에 출력한다.

In [68]:
print(input())

파이썬


**`input()` 함수의 반환값**

`input()` 함수의 반환값은 사용자가 <kbd>Enter</kbd> 키를 치기 전까지
타이핑한 기호들로 구성된 **문자열**이다.

아래 코드를 실행할 때 사용자가 1과 3을 연속으로 입력한 후에 <kbd>Enter</kbd> 키를 치면
문자열 `'13'`이 반환된다.

In [73]:
input("10부터 19 사이의 숫자 하나를 입력하세요: ")

'13'

이런 이유로 `guess_str` 변수에 할당된 값은 정수 13이 아니라 문자열 `'13'`이다.

In [74]:
guess_str

'13'

In [75]:
type(guess_str)

str

### 반환값 변환

문자열 `'13'`을 `secret`에 할당된 정수와 비교하면,
즉, `secret == guess_str`을 실행하면 무조건 `"틀렸습니다!"`가 출력된다.
이유는 정수와 문자열을 비교하면 무조건 `False`로 계산되기 때문이다.

In [76]:
13 == '13'

False

**`int()` 함수 활용**

따라서 `int()` 함수를 이용하여 `input()` 함수의 반환값을 정수형으로 변환한 다음에
`secret` 변수가 가리키는 값과 비교해야 한다.

In [77]:
print(guess == int(guess_str))

True


**`int(input())` 활용**

앞서 입력된 값을 처리하기 위해 두 개의 변수를 사용하였다.

```python
guess_str = input("10부터 19 사이의 숫자 하나를 입력하세요: ") 
guess = int(guess_str)
```

그런데 어차피 정수로 변환된 값을 사용할 것이기에 `guess_str` 변수를 사용하지 않으면서
직접 `guess`를 다음과 같이 정의해도 된다.

```python
guess = int(input("10부터 19 사이의 숫자 하나를 입력하세요: "))
```

이제 `secret` 변수에 저장된 13을 맞히는 코드를 다음과 같이 작성할 수 있다.

In [82]:
print("숫자맞히기 게임에 환영합니다.")

secret = 13
guess = int(input("10부터 19 사이의 숫자 하나를 입력하세요: "))
print("입력한 값:", guess)

if secret == guess:
    print("맞았습니다!")
else:
    print("틀렸습니다!")

숫자맞히기 게임에 환영합니다.
입력한 값: 13
맞았습니다!


물론 13이 아닌 다른 숫자를 입력하면 '틀렸습니다'가 출력된다.
아래 코드는 17일 입력했을 때의 결과를 보여준다.

In [81]:
print("숫자맞히기 게임에 환영합니다.")

secret = 13
guess = int(input("10부터 19 사이의 숫자 하나를 입력하세요: "))
print("입력한 값:", guess)

if secret == guess:
    print("맞았습니다!")
else:
    print("틀렸습니다!")

숫자맞히기 게임에 환영합니다.
입력한 값: 17
틀렸습니다!


**`float()` 함수 활용**

만약에 입력값을 부동소수점으로 변환해야 한다면 `float()` 형변환 함수를 이용한다.
아래 코드를 실행할 때 7을 2로 나눈 값 3.5를 입력하면 `'맞았습니다!'`가 출력된다.

In [83]:
print("나눗셈 질문입니다.")

guess = float(input("7 나누기 2는 얼마인가요? "))
print("입력한 값:", guess)

if guess == 3.5:
    print("맞았습니다!")
else:
    print("틀렸습니다!")

나눗셈 질문입니다.
입력한 값: 3.5
맞았습니다!


만약 `int()`를 사용하면 부동소수점 형식의 문자열 `'3.5'`를 처리할 수 없기에 오류가 발생하기 때문에
입력값의 종류에 맞는 적절한 변환 함수를 사용해야 한다.

In [84]:
print("나눗셈 질문입니다.")

guess = int(input("7 나누기 2는 얼마인가요? "))
print("입력한 값:", guess)

if guess == 3.5:
    print("맞았습니다!")
else:
    print("틀렸습니다!")

나눗셈 질문입니다.


ValueError: invalid literal for int() with base 10: '3.5'

이렇듯 `input()` 함수로 얻어낸 문자열 데이터를 프로그램의 목적에 맞게 `int()`나 `float()`으로 적절히 변환하는 일은 매우 중요하다. 

### 예제

**예제 1**

사용자로부터 하나의 정수를 입력받은 후 입력값이 17보다 크면 
입력값과의 편차의 제곱을, 
아니면 입력된 정수를 그대로 출력하는 코드를 작성한다.

답:

두 정수의 크기비교를 위해 `>` 연산자를 이용한다.
`a`가 표현하는 값이 `b`가 표현하는 값보다 클 때 
표현식 `a > b`가 `True`로 계산된다는 사실을 
`if ... else ...` 조건문에 적용한다.

- 20을 입력할 때

In [ ]:
user_input = int(input("정수 하나를 입력하세요: "))
print("입력한 값:", user_input)

if user_input > 17:
    print('17과의 편차의 제곱:', (user_input - 17)**2)
else:
    print("17보다 크지 않은 값:", user_input)

입력한 값: 20
17과의 편차의 제곱: 9


- 15를 입력할 때

In [ ]:
user_input = int(input("정수 하나를 입력하세요: "))
print("입력한 값:", user_input)

if user_input > 17:
    print('17과의 편차의 제곱:', (user_input - 17)**2)
else:
    print("17보다 크지 않은 값:", user_input)

입력한 값: 15
17보다 크지 않은 값: 15


**예제 2**

아래 기능을 갖는 `format_sum()` 함수를 구현하라.

- 매개변수는 사용하지 않는다.
- 함수를 호출하면 두 개의 정수를 사용자로 입력받는다.
- 입력된 두 개의 정수는 각각 `a`와 `b`로 두 개의 지역변수에 할당한다.
- 반환값은 `a + b = a와b의합` 형식의 문자열이다.

예를 들어 함수를 호출해서 3과 2 두 개의 정수를 각각 입력하면
아래와 같은 문자열이 함수 반환값이 되어야 한다.

```python
3 + 2 = 5
```

힌트: `int()`와 `str()` 두 함수 활용. 

답:

`format_sum()` 함수가 매개변수를 사용하지 않기에 시그니처가 다음과 같다.

```python
def format_sum():
```

`format_sum()` 형식으로 함수가 호출되면
먼저 정수 두 개를 각각 입력받을 수 있도록 `input()` 함수를 두 번 사용한다.
각 입력값을 `a`와 `b`에 차례대로 할당한다.
이때 입력된 값을 정수로 변환하지 않는다.
이유는 반환값이 `a + b = ...` 형식으로 지정되어야 하기 때문에 문자열 연산을 사용해야 하기 때문이다.

반환값을 작성에 필요한 입력값의 합은 `int(a) + int(b)`로 계산하고,
그 결과를 `str()` 함수로 다시 문자열로 변환한다.
즉, 아래 표현식을 활용한다.

```python
str(int(a) + int(b))
```

지금까지의 설명을 정리하여 `format_sum()` 함수를 다음과 같이 정의한다.

In [2]:
def format_sum():
    a = input("첫째 정수를 입력하세요: ")
    b = input("둘째 정수를 입력하세요: ")

    return a + " + " + b + " = " + str(int(a) + int(b))

아래 코드를 실행한 다음에 2와 3을 각각 입력한 결과를 확인하라.

In [3]:
format_sum()

'3 + 2 = 5'

아래 코드를 실행한 다음에 17과 42를 각각 입력한 결과를 확인하라.

In [4]:
format_sum()

'17 + 42 = 59'

**예제 3**

사용자로부터 0이 아닌 한자리 양의 정수 `n` 을 입력받아 `n + nn + nnn` 을 계산하는 코드를 작성한다.
단, `nn`과 `nnn`은 곱셈이 아니고 문자열 `n`을 각각 두 번과 세 번 반복한 결과로 생성된 정수를 가리킨다.
예를 들어 5가 입력되면 아래 값이 출력되어야 한다.

```
5 + 55 + 555 = 615
```

힌트: `int(input())` 형식을 사용하지 않는다.

답:

가. 문자열 `+` 연산자 활용

5를 입력하면 `input()` 함수는 문자열 `'5'`를 입력값으로 지정한다.

    n = input("한 자리 정수 하나를 입력하세요: ")

이제 문자열 `+` 연산자를 이용하여 변수 `n`에 할당된 값을 이어붙인다.
예를 들어 문자열 `'5'`를 이어붙이면 `'55'`가 된다.
여기에 `int()` 함수를 적용하면 정수 55가 계산된다.
유사한 방식으로 정수 555를 계산할 수 있다.

위 설명을 코드로 구현한 다음에 5를 입력하면 언급된 결과가 화면에 출력된다.

In [100]:
n = input("한 자리 정수 하나를 입력하세요: ")
print("입력한 값:", n)

nn = n + n
nnn = nn + n

print(n+' + '+nn+' + '+nnn+' =', int(n) + int(nn) + int(nnn))

입력한 값: 5
5 + 55 + 555 = 615


나. 문자열 `*` 연산자 활용

두 변수 `n`과 `nn`을 `*` 연산자를 이용하여 정의한다.
아래 코드를 실행할 때 7을 입력하면 `7 + 77 + 777 = 861`을 화면에 출력한다.

In [101]:
n = input("한 자리 정수 하나를 입력하세요: ")
print("입력한 값:", n)

nn = n * 2
nnn = n * 3

print(n+' + '+nn+' + '+nnn+' =', int(n) + int(nn) + int(nnn))

입력한 값: 7
7 + 77 + 777 = 861


### 연습문제

**문제 1**

사용자로부터 입력받은 정수에 대한 3의 배수 여부를 판정하는 코드를 작성하라.
단, 3의 배수인 경우와 아닌 경우 각각 다르게 아래 형식으로 출력되도록 한다.

    24 은(는) 3의 배수다.
    
또는

    25 은(는) 3으로 나누면 나머지가 1 이다.

**문제 2**

입력받은 두 부동소수점의 나눗셈을 아래 지정된 형식으로 출력하는 코드를 작성하라.
입력된 값은 각각 변수 `a`와 `b`에 저장한다.
예를 들어 3.3과 5.8이 입력되면 아래처럼 화면에 출력한다.
또한 계산 결과는 소수점 이하 셋째 자리에서 반올림한다.

    3.3 / 5.8 = 0.57

**문제 3**

아래 조건을 만족시키는 `taking_seats()` 함수를 정의하라.

- 매개변수는 사용하지 않는다.
- `taking_seats()` 형식으로 함수 호출이 일어나면 먼저 변수 `N` 지역변수에 할당할 양의 정수를 사용자로부터 입력받는다.
- `N` 변수가 가리키는 정수는 대기실에 일렬로 일렬로 놓여 있는 의자의 개수라 가정한다.
- 반환값은 없다. 대신 함수가 종료하기 전에 아래 조건을 만족하는 두 개의 문자열을 화면에 출력해야 한다.
    - 어느 두 사람도 이웃하여 앉을 수 없다는 조건하에, 앉을 수 있는 최대 인원이 앉는 방식과 최소 인원이 앉는 방식을 표현하는 문자열
    - 단, 자리를 채운 후에는 더 이상 어느 누구도 자리에 앉을 수 없는 방식이어야 함.

예를 들어 의자가 8개인 경우 아래 방식으로 앉는 것은 허용되지 않는다.
아래 표에서 `O`은 채워진 자리를, `X`는 빈자리를 가리킨다.

| 불가능 방식 | 이유 |
| :---: | :--- |
| `XXOXOXOX` | 왼쪽 끝에 한 명 더 앉을 수 있음 |
| `XOXXOXXX` | 오른쪽 끝에 한 명 더 앉을 수 있음|

의자가 8 개일 때 의자에 앉을 수 있는 최소 인원과 최대 인원은 다음과 같다.

| 인원 | 앉는 방식 |
| :---: | :---: |
| 최소 3명 | `XOXXOXXO` |
| 최대 4명 | `OXOXOXOX` |

따라서 함수가 호출되고 8을 입력하면 화면에 아래와 같이 출력되어야 한다.

```
입력한 값: 8
최대 인원 4 명: OXOXOXOX
최소 인원 3 명: XOXXOXXO
```

## 람다 함수

특별한 목적으로 한 번만 사용되는 함수가 필요할 때, 
그리고 함수의 본문이 `return 표현식`으로만 구성될 정도로 매우 단순할 때,
함수의 이름을 지정하지 않으면서 
아래 형식으로 함수를 정의해서 활용한다.

```python
lambda 매개변수1, ..., 매개변수n : 표현식
```

lambda(람다)는 그리스어 알파벳 &#955;를 가리키며,
람다 알파벳을 사용한다는 이유로 
**람다 함수**<font size='2'>lambda function</font>라 부른다.

예를 들어 두 인자의 곱을 반환하는 람다 함수는 아래와 같이 정의된다.

- `a`와 `b`: 매개변수 2개
- 콜론 기호 (`:`) 뒤의 표현식 `a * b`: 람다 함수의 반환값

In [ ]:
lambda a, b : a * b

<function __main__.<lambda>(a, b)>

위 코드는 아래 `lambda_func()` 함수와 동일한 기능을 수행한다.
두 함수는 이름이 있느냐 없느냐의 차이만 갖는다.

In [ ]:
def lambda_func(a, b):
    return a * b

람다 함수는 자신을 가리키는 이름이 없기에 람다 함수를 호출하려면 항상 람다 함수 정의 자체를 함수 이름으로 사용해야 해서 조금 불편하다.
예를 들어, 아래 코드는 2와 5의 곱을 계산하는 람다 함수 호출식이다.

In [ ]:
(lambda a, b : a * b)(2, 5)

10

**값으로서의 함수**

파이썬에서 모든 것이 값이다라고 몇 번 언급했다.
예를 들어, `1`, `2`, `3`, `1.2`, `3.141592`, `'python'`, `'좋아요'`, `[1, 3, 5, 7]` 등을 포함해서, `int`, `float`, `str`, `list` 등 심지어 자료형을 가리키는 것까지 모두 값이다.
이에 더해 여기서 배우는 함수 또한 하나의 값이며, 앞으로 다른 종류의 값들도 다룰 예정이다.

함수 또한 값이기에 변수 할당에 활용될 수 있다.
아래 코드는 앞서 정의한 람다 함수를 변수에 할당하여
람다 함수 정의대신 변수를 일반적인 함수 호출처럼 사용한다.

In [ ]:
lambda_add = lambda a, b : a * b
print(lambda_add(2, 5))

10


:::{note} 일급 객체

변수에 저장할 수 있고, 따라서 함수의 인자로 사용할 수 있는 대상이 값이며, 파이썬에서 다루는 모든 대상이 값이다.
반면에 C 언어의 경우엔 함수를 변수에 할당하거나 다른 함수의 인자로 사용할 수 없고,
대신 포인터 변수라는 특별한 장치를 활용해서 함수를 변수에 할당하거나 다른 함수의 인자로 활용한다.

이처럼 프로그래밍언어마다 값으로 인정되는 종류와 범위가 다른데,
변수 할당과 함수의 인자로 특별한 장치 없이 바로 사용할 수 있다는 점에서
값을 **일급 객체**, 영어로 **first-class citizen**이라 부른다.

정리하면, 함수를 포함해서 파이썬에서는 모든 대상이 값이자 동시에 일급 객체다.
:::

**인자로서의 함수**

함수 또한 일종의 값이기 때문에 다른 함수의 인자로 사용될 수 있다.
예를 들어, 아래 `apply_func()` 함수는 첫째 매개변수는 함수를 인자로 받고,
둘째 매개변수는 첫째 인자로 지정된 함수의 인자로 사용할 수 있는 값을 인자로 받는다.
반환값은 첫째 인자로 들어온 함수를 둘째 인자로 지정된 값과 함께 호출했을 때의
반환값으로 지정된다.

In [4]:
def apply_func(func, value):
    return func(value)

`apply_func()` 함수를 호출하는 방식도 다를 바가 없다. 
첫째 인자로 어떤 함수를, 둘째 인자로 첫째 인자로 지정된 함수의 인자로 사용될 수 있는 값을 지정하면 된다.

예를 들어, 아래 코드에서 `double` 변수는 지정된 인자를 두 배한 값을 반환하는 람다 함수를 가리킨다.
따라서 `apply_func(double, 3)`의 반환값은 `double(3)`, 즉 6을 반환한다.

In [5]:
double = lambda x: x * 2

result = apply_func(double, 3)
print("3을 2배한 값:", result)  # 3 -> 6

3을 2배한 값: 6


위 코드에서 `double` 변수가 람다 함수를 가리키기에 `double` 변수 대신 해당 람다 함수를 직접
`apply_func()` 함수의 인자로 지정해도 된다.
다만, 코드가 조금 복잡해질 뿐이다.

In [6]:
apply_func(lambda x: x * 2, 3)

6

`apply_func()` 함수의 첫째 인자로 다른 함수를 지정하면 당연히 다른 결과가 나온다.
아래 코드에서 `add_ten()` 함수는 인자에 10을 더한 값을 반환한다.
따라서 아래 코드를 실행하면 5에 10을 더한 15가 
`result2` 변수에 할당된다.

In [8]:
def add_ten(x):
    return x + 10

result2 = apply_func(add_ten, 5)
print("5에 10을 더하기:", result2)  # 5 -> 15

5에 10을 더하기: 15


### 예제

**예제 1**

섭씨(celsius)를 화씨(fahrenheit)로 변환하는 수식은 다음과 같다.

```python
섭씨 * 9 / 5 + 32
```

섭씨 26도를 화씨로 변환하기 위해
위 수식을 반환값으로 갖는 다음 람다 함수를 활용하라.

답:

섭씨를 화씨로 변환하는 람다 함수는 아래처럼 작성한다.

In [ ]:
lambda c: c * 9 / 5 + 32

<function __main__.<lambda>(c)>

아래 코드는 위 람다 함수를 26을 인자로 해서 호출하면 화씨를 계산한다.

In [ ]:
celsius = 26
fahrenheit = (lambda c: c * 9 / 5 + 32)(celsius)

print("섭씨:", celsius, '도')
print("화씨:", fahrenheit, '도')

섭씨: 26 도
화씨: 78.8 도


**예제 2**

화씨를 섭씨로 변환하는 람다 함수를 `lambda_celsius` 변수에 할당한 다음에
화씨 80도에 해당하는 섭씨 온도를 계산하라.
단, 계산 결과는 소수점 이하 셋째 자리에서 반올림한다.

답:

먼저 섭씨를 화씨로 변환하는 과정을 역으로 수행하는 수식은 다음과 같다.

```python
(화씨 - 32) * 5 / 9
```

위 식을 반환값으로 갖는 람다 함수를 가리키는 변수 `lambda_celsius`에 다음과 같이 할당한다.

In [ ]:
lambda_celsius = lambda f: (f - 32) * 5 / 9

정의된 변수를 활용하여 화씨 80도를 섭씨로 변환한 결과를 아래 코드처럼 확인할 수 있다.
`round()` 함수를 이용하여 소수점 이하 둘째 자리까지만 화면에 출력한다.

In [ ]:
fahrenheit = 80

celsius = lambda_celsius(fahrenheit)
print("화씨:", fahrenheit, '도')
print("섭씨:", round(celsius, 2), '도')


화씨: 80 도
섭씨: 26.67 도


**예제 3**

아래 `apply_twice()` 함수는 함수를 인자로 받아서
그 함수를 두 번 연속으로 실행한다.
아래 코드의 실행 결과를 설명하라.

In [13]:
def apply_twice(func, value):
    return func(func(value))

double = lambda x: x * 2

result = apply_twice(double, 3)
print("3을 2배하기를 두 번 적용한 값:", result)

3을 2배하기를 두 번 적용한 값: 12


답:

코드가 실행되는 과정은 다음과 같다.

- `double` 변수는 입력값을 2배로 만드는 함수를 가리킨다.
- `apply_twice(double, 3)` 는 `double`이 가리키는 함수를 값 `3`에 두 번 연속 적용한다.
    - 첫 번째 적용: `double(3) = 6`
    - 두 번째 적용: `double(6) = 12`
- `result`에는 `12`가 할당되고, 출력 결과는 다음과 같다.

        3을 2배하기를 두 번 적용한 값: 12

### 연습문제

**문제 1**

평수를 제곱미터로 변환하는 코드를 람다 함수를 이용하여 작성하라. 
단, 25평을 제곱미터로 변환해야 하며,
소수점 이하 둘째자리까지만 계산한다.
평을 제곱미터로 변환하는 공식은 다음과 같다.

```python
평수 * 3.3058
```

**문제 2**

제곱미터를 평으로 변환하는 람다 함수를 `lambda_pyeong` 변수에 할당한 다음에
그 변수를 이용하여 90 제곱미터가 몇 평이 되는지 계산하는 코드를 작성하라.
단, 소수점 이하 둘째 자리까지만 계산한다.

**문제 3**

함수를 인자로 사용하는 함수에 대한 문제다.

(1) 아래 `apply_chain()` 함수의 시그니처와 기능을 설명하라.

In [ ]:
def apply_chain(func1, func2, value):
    return func2(func1(value))

(2) 아래 코드의 실행 결과를 설명하라.

In [22]:
print(apply_chain(lambda c: c * 9 / 5 + 32, lambda f: round(f, 1), 26.3))

79.3
